#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.Controller
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class ModeloRecursosHumanosEASJDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertSJ_Usuario(SJ_Usuario instance);
    partial void UpdateSJ_Usuario(SJ_Usuario instance);
    partial void DeleteSJ_Usuario(SJ_Usuario instance);
    partial void InsertEMPRESAS(EMPRESAS instance);
    partial void UpdateEMPRESAS(EMPRESAS instance);
    partial void DeleteEMPRESAS(EMPRESAS instance);
    #endregion
		
		public ModeloRecursosHumanosEASJDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloRecursosHumanosEASJDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloRecursosHumanosEASJDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloRecursosHumanosEASJDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SJ_Usuario> SJ_Usuario
		{
			get
			{
				return this.GetTable<SJ_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<EMPRESAS> EMPRESAS
		{
			get
			{
				return this.GetTable<EMPRESAS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_Usuario")]
	public partial class SJ_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdUsuario;
		
		private string _Password;
		
		private string _Dni;
		
		private int _Estado;
		
		private string _UserNombres;
		
		private System.DateTime _FechaCreacion;
		
		private string _IdArea;
		
		private System.Nullable<char> _NivelAcceso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDniChanging(string value);
    partial void OnDniChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnUserNombresChanging(string value);
    partial void OnUserNombresChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnIdAreaChanging(string value);
    partial void OnIdAreaChanged();
    partial void OnNivelAccesoChanging(System.Nullable<char> value);
    partial void OnNivelAccesoChanged();
    #endregion
		
		public SJ_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dni", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string Dni
		{
			get
			{
				return this._Dni;
			}
			set
			{
				if ((this._Dni != value))
				{
					this.OnDniChanging(value);
					this.SendPropertyChanging();
					this._Dni = value;
					this.SendPropertyChanged("Dni");
					this.OnDniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNombres", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string UserNombres
		{
			get
			{
				return this._UserNombres;
			}
			set
			{
				if ((this._UserNombres != value))
				{
					this.OnUserNombresChanging(value);
					this.SendPropertyChanging();
					this._UserNombres = value;
					this.SendPropertyChanged("UserNombres");
					this.OnUserNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Char(4)")]
		public string IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelAcceso", DbType="Char(1)")]
		public System.Nullable<char> NivelAcceso
		{
			get
			{
				return this._NivelAcceso;
			}
			set
			{
				if ((this._NivelAcceso != value))
				{
					this.OnNivelAccesoChanging(value);
					this.SendPropertyChanging();
					this._NivelAcceso = value;
					this.SendPropertyChanged("NivelAcceso");
					this.OnNivelAccesoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPRESAS")]
	public partial class EMPRESAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDEMPRESA;
		
		private string _RAZON_SOCIAL;
		
		private string _RUC;
		
		private string _DIRECCION;
		
		private string _REPRESENTANTE;
		
		private string _DOCIDENTIDAD;
		
		private string _E_MAIL;
		
		private string _TELEFONO;
		
		private string _FAX;
		
		private System.Nullable<decimal> _ESTADO;
		
		private string _RUTAREPORTES;
		
		private System.Nullable<System.DateTime> _FECHACREACION;
		
		private string _RUTAPRODUCTOS;
		
		private string _RUTAEMPLEADOS;
		
		private string _RUTADOCUMENTOS;
		
		private string _SERVIDORBD;
		
		private string _BASEDATOS;
		
		private string _IDTIPOESTABLECIMIENTO;
		
		private string _CODESTABLECIMIENTO;
		
		private System.Nullable<decimal> _DOMICILIOFISCAL;
		
		private string _IDCONDICIONESTABLECIMIENTO;
		
		private string _IDVIA;
		
		private System.Nullable<decimal> _NUMERO;
		
		private System.Nullable<decimal> _INTERIOR;
		
		private string _IDZONA;
		
		private string _NOMBREZONA;
		
		private string _REFERENCIA;
		
		private string _IDUBIGEO;
		
		private string _DOCIDENTIDAD2;
		
		private string _REPRESENTANTE2;
		
		private string _IDCLIEPROV;
		
		private System.Nullable<decimal> _CON_SENATI;
		
		private string _RUTABACKUP;
		
		private string _USUARIOFTP;
		
		private string _PASSFTP;
		
		private string _RUTARELOJ;
		
		private string _RUTAGANADO;
		
		private string _BDWEBSERVICE;
		
		private string _IDBASEDATOS;
		
		private string _USUARIO_SOL;
		
		private string _cod_empresa;
		
		private string _nombre_corto;
		
		private System.Nullable<decimal> _usa_cismovil;
		
		private System.Nullable<decimal> _usa_tareomovil;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEMPRESAChanging(string value);
    partial void OnIDEMPRESAChanged();
    partial void OnRAZON_SOCIALChanging(string value);
    partial void OnRAZON_SOCIALChanged();
    partial void OnRUCChanging(string value);
    partial void OnRUCChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnREPRESENTANTEChanging(string value);
    partial void OnREPRESENTANTEChanged();
    partial void OnDOCIDENTIDADChanging(string value);
    partial void OnDOCIDENTIDADChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnESTADOChanging(System.Nullable<decimal> value);
    partial void OnESTADOChanged();
    partial void OnRUTAREPORTESChanging(string value);
    partial void OnRUTAREPORTESChanged();
    partial void OnFECHACREACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHACREACIONChanged();
    partial void OnRUTAPRODUCTOSChanging(string value);
    partial void OnRUTAPRODUCTOSChanged();
    partial void OnRUTAEMPLEADOSChanging(string value);
    partial void OnRUTAEMPLEADOSChanged();
    partial void OnRUTADOCUMENTOSChanging(string value);
    partial void OnRUTADOCUMENTOSChanged();
    partial void OnSERVIDORBDChanging(string value);
    partial void OnSERVIDORBDChanged();
    partial void OnBASEDATOSChanging(string value);
    partial void OnBASEDATOSChanged();
    partial void OnIDTIPOESTABLECIMIENTOChanging(string value);
    partial void OnIDTIPOESTABLECIMIENTOChanged();
    partial void OnCODESTABLECIMIENTOChanging(string value);
    partial void OnCODESTABLECIMIENTOChanged();
    partial void OnDOMICILIOFISCALChanging(System.Nullable<decimal> value);
    partial void OnDOMICILIOFISCALChanged();
    partial void OnIDCONDICIONESTABLECIMIENTOChanging(string value);
    partial void OnIDCONDICIONESTABLECIMIENTOChanged();
    partial void OnIDVIAChanging(string value);
    partial void OnIDVIAChanged();
    partial void OnNUMEROChanging(System.Nullable<decimal> value);
    partial void OnNUMEROChanged();
    partial void OnINTERIORChanging(System.Nullable<decimal> value);
    partial void OnINTERIORChanged();
    partial void OnIDZONAChanging(string value);
    partial void OnIDZONAChanged();
    partial void OnNOMBREZONAChanging(string value);
    partial void OnNOMBREZONAChanged();
    partial void OnREFERENCIAChanging(string value);
    partial void OnREFERENCIAChanged();
    partial void OnIDUBIGEOChanging(string value);
    partial void OnIDUBIGEOChanged();
    partial void OnDOCIDENTIDAD2Changing(string value);
    partial void OnDOCIDENTIDAD2Changed();
    partial void OnREPRESENTANTE2Changing(string value);
    partial void OnREPRESENTANTE2Changed();
    partial void OnIDCLIEPROVChanging(string value);
    partial void OnIDCLIEPROVChanged();
    partial void OnCON_SENATIChanging(System.Nullable<decimal> value);
    partial void OnCON_SENATIChanged();
    partial void OnRUTABACKUPChanging(string value);
    partial void OnRUTABACKUPChanged();
    partial void OnUSUARIOFTPChanging(string value);
    partial void OnUSUARIOFTPChanged();
    partial void OnPASSFTPChanging(string value);
    partial void OnPASSFTPChanged();
    partial void OnRUTARELOJChanging(string value);
    partial void OnRUTARELOJChanged();
    partial void OnRUTAGANADOChanging(string value);
    partial void OnRUTAGANADOChanged();
    partial void OnBDWEBSERVICEChanging(string value);
    partial void OnBDWEBSERVICEChanged();
    partial void OnIDBASEDATOSChanging(string value);
    partial void OnIDBASEDATOSChanged();
    partial void OnUSUARIO_SOLChanging(string value);
    partial void OnUSUARIO_SOLChanged();
    partial void Oncod_empresaChanging(string value);
    partial void Oncod_empresaChanged();
    partial void Onnombre_cortoChanging(string value);
    partial void Onnombre_cortoChanged();
    partial void Onusa_cismovilChanging(System.Nullable<decimal> value);
    partial void Onusa_cismovilChanged();
    partial void Onusa_tareomovilChanging(System.Nullable<decimal> value);
    partial void Onusa_tareomovilChanged();
    #endregion
		
		public EMPRESAS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPRESA", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDEMPRESA
		{
			get
			{
				return this._IDEMPRESA;
			}
			set
			{
				if ((this._IDEMPRESA != value))
				{
					this.OnIDEMPRESAChanging(value);
					this.SendPropertyChanging();
					this._IDEMPRESA = value;
					this.SendPropertyChanged("IDEMPRESA");
					this.OnIDEMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAZON_SOCIAL", DbType="VarChar(50)")]
		public string RAZON_SOCIAL
		{
			get
			{
				return this._RAZON_SOCIAL;
			}
			set
			{
				if ((this._RAZON_SOCIAL != value))
				{
					this.OnRAZON_SOCIALChanging(value);
					this.SendPropertyChanging();
					this._RAZON_SOCIAL = value;
					this.SendPropertyChanged("RAZON_SOCIAL");
					this.OnRAZON_SOCIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="Char(11)")]
		public string RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this.OnRUCChanging(value);
					this.SendPropertyChanging();
					this._RUC = value;
					this.SendPropertyChanged("RUC");
					this.OnRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPRESENTANTE", DbType="VarChar(100)")]
		public string REPRESENTANTE
		{
			get
			{
				return this._REPRESENTANTE;
			}
			set
			{
				if ((this._REPRESENTANTE != value))
				{
					this.OnREPRESENTANTEChanging(value);
					this.SendPropertyChanging();
					this._REPRESENTANTE = value;
					this.SendPropertyChanged("REPRESENTANTE");
					this.OnREPRESENTANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCIDENTIDAD", DbType="VarChar(20)")]
		public string DOCIDENTIDAD
		{
			get
			{
				return this._DOCIDENTIDAD;
			}
			set
			{
				if ((this._DOCIDENTIDAD != value))
				{
					this.OnDOCIDENTIDADChanging(value);
					this.SendPropertyChanging();
					this._DOCIDENTIDAD = value;
					this.SendPropertyChanged("DOCIDENTIDAD");
					this.OnDOCIDENTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MAIL", DbType="VarChar(50)")]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="Char(12)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="Char(12)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTAREPORTES", DbType="VarChar(200)")]
		public string RUTAREPORTES
		{
			get
			{
				return this._RUTAREPORTES;
			}
			set
			{
				if ((this._RUTAREPORTES != value))
				{
					this.OnRUTAREPORTESChanging(value);
					this.SendPropertyChanging();
					this._RUTAREPORTES = value;
					this.SendPropertyChanged("RUTAREPORTES");
					this.OnRUTAREPORTESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHACREACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHACREACION
		{
			get
			{
				return this._FECHACREACION;
			}
			set
			{
				if ((this._FECHACREACION != value))
				{
					this.OnFECHACREACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHACREACION = value;
					this.SendPropertyChanged("FECHACREACION");
					this.OnFECHACREACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTAPRODUCTOS", DbType="VarChar(200)")]
		public string RUTAPRODUCTOS
		{
			get
			{
				return this._RUTAPRODUCTOS;
			}
			set
			{
				if ((this._RUTAPRODUCTOS != value))
				{
					this.OnRUTAPRODUCTOSChanging(value);
					this.SendPropertyChanging();
					this._RUTAPRODUCTOS = value;
					this.SendPropertyChanged("RUTAPRODUCTOS");
					this.OnRUTAPRODUCTOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTAEMPLEADOS", DbType="VarChar(200)")]
		public string RUTAEMPLEADOS
		{
			get
			{
				return this._RUTAEMPLEADOS;
			}
			set
			{
				if ((this._RUTAEMPLEADOS != value))
				{
					this.OnRUTAEMPLEADOSChanging(value);
					this.SendPropertyChanging();
					this._RUTAEMPLEADOS = value;
					this.SendPropertyChanged("RUTAEMPLEADOS");
					this.OnRUTAEMPLEADOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTADOCUMENTOS", DbType="VarChar(200)")]
		public string RUTADOCUMENTOS
		{
			get
			{
				return this._RUTADOCUMENTOS;
			}
			set
			{
				if ((this._RUTADOCUMENTOS != value))
				{
					this.OnRUTADOCUMENTOSChanging(value);
					this.SendPropertyChanging();
					this._RUTADOCUMENTOS = value;
					this.SendPropertyChanged("RUTADOCUMENTOS");
					this.OnRUTADOCUMENTOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVIDORBD", DbType="VarChar(100)")]
		public string SERVIDORBD
		{
			get
			{
				return this._SERVIDORBD;
			}
			set
			{
				if ((this._SERVIDORBD != value))
				{
					this.OnSERVIDORBDChanging(value);
					this.SendPropertyChanging();
					this._SERVIDORBD = value;
					this.SendPropertyChanged("SERVIDORBD");
					this.OnSERVIDORBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASEDATOS", DbType="VarChar(100)")]
		public string BASEDATOS
		{
			get
			{
				return this._BASEDATOS;
			}
			set
			{
				if ((this._BASEDATOS != value))
				{
					this.OnBASEDATOSChanging(value);
					this.SendPropertyChanging();
					this._BASEDATOS = value;
					this.SendPropertyChanged("BASEDATOS");
					this.OnBASEDATOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPOESTABLECIMIENTO", DbType="Char(2)")]
		public string IDTIPOESTABLECIMIENTO
		{
			get
			{
				return this._IDTIPOESTABLECIMIENTO;
			}
			set
			{
				if ((this._IDTIPOESTABLECIMIENTO != value))
				{
					this.OnIDTIPOESTABLECIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPOESTABLECIMIENTO = value;
					this.SendPropertyChanged("IDTIPOESTABLECIMIENTO");
					this.OnIDTIPOESTABLECIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODESTABLECIMIENTO", DbType="Char(4)")]
		public string CODESTABLECIMIENTO
		{
			get
			{
				return this._CODESTABLECIMIENTO;
			}
			set
			{
				if ((this._CODESTABLECIMIENTO != value))
				{
					this.OnCODESTABLECIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._CODESTABLECIMIENTO = value;
					this.SendPropertyChanged("CODESTABLECIMIENTO");
					this.OnCODESTABLECIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIOFISCAL", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> DOMICILIOFISCAL
		{
			get
			{
				return this._DOMICILIOFISCAL;
			}
			set
			{
				if ((this._DOMICILIOFISCAL != value))
				{
					this.OnDOMICILIOFISCALChanging(value);
					this.SendPropertyChanging();
					this._DOMICILIOFISCAL = value;
					this.SendPropertyChanged("DOMICILIOFISCAL");
					this.OnDOMICILIOFISCALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCONDICIONESTABLECIMIENTO", DbType="Char(2)")]
		public string IDCONDICIONESTABLECIMIENTO
		{
			get
			{
				return this._IDCONDICIONESTABLECIMIENTO;
			}
			set
			{
				if ((this._IDCONDICIONESTABLECIMIENTO != value))
				{
					this.OnIDCONDICIONESTABLECIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._IDCONDICIONESTABLECIMIENTO = value;
					this.SendPropertyChanged("IDCONDICIONESTABLECIMIENTO");
					this.OnIDCONDICIONESTABLECIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVIA", DbType="Char(2)")]
		public string IDVIA
		{
			get
			{
				return this._IDVIA;
			}
			set
			{
				if ((this._IDVIA != value))
				{
					this.OnIDVIAChanging(value);
					this.SendPropertyChanging();
					this._IDVIA = value;
					this.SendPropertyChanged("IDVIA");
					this.OnIDVIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this.OnNUMEROChanging(value);
					this.SendPropertyChanging();
					this._NUMERO = value;
					this.SendPropertyChanged("NUMERO");
					this.OnNUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERIOR", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> INTERIOR
		{
			get
			{
				return this._INTERIOR;
			}
			set
			{
				if ((this._INTERIOR != value))
				{
					this.OnINTERIORChanging(value);
					this.SendPropertyChanging();
					this._INTERIOR = value;
					this.SendPropertyChanged("INTERIOR");
					this.OnINTERIORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDZONA", DbType="Char(2)")]
		public string IDZONA
		{
			get
			{
				return this._IDZONA;
			}
			set
			{
				if ((this._IDZONA != value))
				{
					this.OnIDZONAChanging(value);
					this.SendPropertyChanging();
					this._IDZONA = value;
					this.SendPropertyChanged("IDZONA");
					this.OnIDZONAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBREZONA", DbType="VarChar(50)")]
		public string NOMBREZONA
		{
			get
			{
				return this._NOMBREZONA;
			}
			set
			{
				if ((this._NOMBREZONA != value))
				{
					this.OnNOMBREZONAChanging(value);
					this.SendPropertyChanging();
					this._NOMBREZONA = value;
					this.SendPropertyChanged("NOMBREZONA");
					this.OnNOMBREZONAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERENCIA", DbType="VarChar(100)")]
		public string REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this.OnREFERENCIAChanging(value);
					this.SendPropertyChanging();
					this._REFERENCIA = value;
					this.SendPropertyChanged("REFERENCIA");
					this.OnREFERENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUBIGEO", DbType="Char(6)")]
		public string IDUBIGEO
		{
			get
			{
				return this._IDUBIGEO;
			}
			set
			{
				if ((this._IDUBIGEO != value))
				{
					this.OnIDUBIGEOChanging(value);
					this.SendPropertyChanging();
					this._IDUBIGEO = value;
					this.SendPropertyChanged("IDUBIGEO");
					this.OnIDUBIGEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCIDENTIDAD2", DbType="VarChar(20)")]
		public string DOCIDENTIDAD2
		{
			get
			{
				return this._DOCIDENTIDAD2;
			}
			set
			{
				if ((this._DOCIDENTIDAD2 != value))
				{
					this.OnDOCIDENTIDAD2Changing(value);
					this.SendPropertyChanging();
					this._DOCIDENTIDAD2 = value;
					this.SendPropertyChanged("DOCIDENTIDAD2");
					this.OnDOCIDENTIDAD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPRESENTANTE2", DbType="VarChar(100)")]
		public string REPRESENTANTE2
		{
			get
			{
				return this._REPRESENTANTE2;
			}
			set
			{
				if ((this._REPRESENTANTE2 != value))
				{
					this.OnREPRESENTANTE2Changing(value);
					this.SendPropertyChanging();
					this._REPRESENTANTE2 = value;
					this.SendPropertyChanged("REPRESENTANTE2");
					this.OnREPRESENTANTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIEPROV", DbType="Char(11)")]
		public string IDCLIEPROV
		{
			get
			{
				return this._IDCLIEPROV;
			}
			set
			{
				if ((this._IDCLIEPROV != value))
				{
					this.OnIDCLIEPROVChanging(value);
					this.SendPropertyChanging();
					this._IDCLIEPROV = value;
					this.SendPropertyChanged("IDCLIEPROV");
					this.OnIDCLIEPROVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CON_SENATI", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> CON_SENATI
		{
			get
			{
				return this._CON_SENATI;
			}
			set
			{
				if ((this._CON_SENATI != value))
				{
					this.OnCON_SENATIChanging(value);
					this.SendPropertyChanging();
					this._CON_SENATI = value;
					this.SendPropertyChanged("CON_SENATI");
					this.OnCON_SENATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTABACKUP", DbType="VarChar(200)")]
		public string RUTABACKUP
		{
			get
			{
				return this._RUTABACKUP;
			}
			set
			{
				if ((this._RUTABACKUP != value))
				{
					this.OnRUTABACKUPChanging(value);
					this.SendPropertyChanging();
					this._RUTABACKUP = value;
					this.SendPropertyChanged("RUTABACKUP");
					this.OnRUTABACKUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOFTP", DbType="VarChar(200)")]
		public string USUARIOFTP
		{
			get
			{
				return this._USUARIOFTP;
			}
			set
			{
				if ((this._USUARIOFTP != value))
				{
					this.OnUSUARIOFTPChanging(value);
					this.SendPropertyChanging();
					this._USUARIOFTP = value;
					this.SendPropertyChanged("USUARIOFTP");
					this.OnUSUARIOFTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSFTP", DbType="Char(20)")]
		public string PASSFTP
		{
			get
			{
				return this._PASSFTP;
			}
			set
			{
				if ((this._PASSFTP != value))
				{
					this.OnPASSFTPChanging(value);
					this.SendPropertyChanging();
					this._PASSFTP = value;
					this.SendPropertyChanged("PASSFTP");
					this.OnPASSFTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTARELOJ", DbType="VarChar(200)")]
		public string RUTARELOJ
		{
			get
			{
				return this._RUTARELOJ;
			}
			set
			{
				if ((this._RUTARELOJ != value))
				{
					this.OnRUTARELOJChanging(value);
					this.SendPropertyChanging();
					this._RUTARELOJ = value;
					this.SendPropertyChanged("RUTARELOJ");
					this.OnRUTARELOJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTAGANADO", DbType="VarChar(200)")]
		public string RUTAGANADO
		{
			get
			{
				return this._RUTAGANADO;
			}
			set
			{
				if ((this._RUTAGANADO != value))
				{
					this.OnRUTAGANADOChanging(value);
					this.SendPropertyChanging();
					this._RUTAGANADO = value;
					this.SendPropertyChanged("RUTAGANADO");
					this.OnRUTAGANADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDWEBSERVICE", DbType="VarChar(50)")]
		public string BDWEBSERVICE
		{
			get
			{
				return this._BDWEBSERVICE;
			}
			set
			{
				if ((this._BDWEBSERVICE != value))
				{
					this.OnBDWEBSERVICEChanging(value);
					this.SendPropertyChanging();
					this._BDWEBSERVICE = value;
					this.SendPropertyChanged("BDWEBSERVICE");
					this.OnBDWEBSERVICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBASEDATOS", DbType="VarChar(100)")]
		public string IDBASEDATOS
		{
			get
			{
				return this._IDBASEDATOS;
			}
			set
			{
				if ((this._IDBASEDATOS != value))
				{
					this.OnIDBASEDATOSChanging(value);
					this.SendPropertyChanging();
					this._IDBASEDATOS = value;
					this.SendPropertyChanged("IDBASEDATOS");
					this.OnIDBASEDATOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_SOL", DbType="VarChar(25)")]
		public string USUARIO_SOL
		{
			get
			{
				return this._USUARIO_SOL;
			}
			set
			{
				if ((this._USUARIO_SOL != value))
				{
					this.OnUSUARIO_SOLChanging(value);
					this.SendPropertyChanging();
					this._USUARIO_SOL = value;
					this.SendPropertyChanged("USUARIO_SOL");
					this.OnUSUARIO_SOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_empresa", DbType="Char(3)")]
		public string cod_empresa
		{
			get
			{
				return this._cod_empresa;
			}
			set
			{
				if ((this._cod_empresa != value))
				{
					this.Oncod_empresaChanging(value);
					this.SendPropertyChanging();
					this._cod_empresa = value;
					this.SendPropertyChanged("cod_empresa");
					this.Oncod_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_corto", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string nombre_corto
		{
			get
			{
				return this._nombre_corto;
			}
			set
			{
				if ((this._nombre_corto != value))
				{
					this.Onnombre_cortoChanging(value);
					this.SendPropertyChanging();
					this._nombre_corto = value;
					this.SendPropertyChanged("nombre_corto");
					this.Onnombre_cortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usa_cismovil", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> usa_cismovil
		{
			get
			{
				return this._usa_cismovil;
			}
			set
			{
				if ((this._usa_cismovil != value))
				{
					this.Onusa_cismovilChanging(value);
					this.SendPropertyChanging();
					this._usa_cismovil = value;
					this.SendPropertyChanged("usa_cismovil");
					this.Onusa_cismovilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usa_tareomovil", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> usa_tareomovil
		{
			get
			{
				return this._usa_tareomovil;
			}
			set
			{
				if ((this._usa_tareomovil != value))
				{
					this.Onusa_tareomovilChanging(value);
					this.SendPropertyChanging();
					this._usa_tareomovil = value;
					this.SendPropertyChanged("usa_tareomovil");
					this.Onusa_tareomovilChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
