<?xml version="1.0" encoding="utf-8"?><Database Class="ModeloRecursosHumanosEASJDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.SJ_Usuario" Member="SJ_Usuario">
    <Type Name="SJ_Usuario">
      <Column Name="IdUsuario" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Dni" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserNombres" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdArea" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="NivelAcceso" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPRESAS" Member="EMPRESAS">
    <Type Name="EMPRESAS">
      <Column Name="IDEMPRESA" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RAZON_SOCIAL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RUC" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REPRESENTANTE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOCIDENTIDAD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="RUTAREPORTES" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FECHACREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RUTAPRODUCTOS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RUTAEMPLEADOS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RUTADOCUMENTOS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SERVIDORBD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BASEDATOS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDTIPOESTABLECIMIENTO" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="CODESTABLECIMIENTO" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="DOMICILIOFISCAL" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="IDCONDICIONESTABLECIMIENTO" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="IDVIA" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="NUMERO" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="INTERIOR" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="IDZONA" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="NOMBREZONA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REFERENCIA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDUBIGEO" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="DOCIDENTIDAD2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="REPRESENTANTE2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDCLIEPROV" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="CON_SENATI" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="RUTABACKUP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="USUARIOFTP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PASSFTP" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="RUTARELOJ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RUTAGANADO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BDWEBSERVICE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDBASEDATOS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USUARIO_SOL" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="cod_empresa" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="nombre_corto" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="usa_cismovil" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="usa_tareomovil" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>