//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa")]
        public string ExoticsProducerPackingConnectionString2 {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=estanisl@o.2021")]
        public string ExoticsProducerPackingConnectionString3 {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=estanisl@o.2021")]
        public string ESTANISLAO2017ConnectionString1 {
            get {
                return ((string)(this["ESTANISLAO2017ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=15022006")]
        public string agricolasanjuan2014ConnectionString {
            get {
                return ((string)(this["agricolasanjuan2014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=amadeus2010")]
        public string ESTANISLAO2017ConnectionString {
            get {
                return ((string)(this["ESTANISLAO2017ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=estanisl@o.2021")]
        public string ESTANISLAO2017ConnectionString2 {
            get {
                return ((string)(this["ESTANISLAO2017ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;In" +
            "tegrated Security=True")]
        public string ExoticsProducerPackingConnectionString {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005\\MSSQLSERVER2014;Initial Catalog=ExoticsProducerPacking;Pe" +
            "rsist Security Info=True;User ID=sa;Password=estanisl@o.2021")]
        public string ExoticsProducerPackingConnectionString1 {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESTCHIMU005;Initial Catalog=ExoticsProducerPacking;Persist Security I" +
            "nfo=True;User ID=sa;Password=estanisl@o.2021")]
        public string ExoticsProducerPackingConnectionString4 {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=68.168.108.52;Initial Catalog=ExoticsProducerPacking;Persist Security" +
            " Info=True;User ID=sa;Password=.1975Casa")]
        public string ExoticsProducerPackingConnectionBlueSoft {
            get {
                return ((string)(this["ExoticsProducerPackingConnectionBlueSoft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=162.244.65.140;Initial Catalog=ControlAsistencia;Persist Security Inf" +
            "o=True;User ID=sa;Password=Ag1c0l@18tz")]
        public string ControlAsistenciaConnectionString {
            get {
                return ((string)(this["ControlAsistenciaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=68.168.108.52;Initial Catalog=AGRICOLA2017;Persist Security Info=True" +
            ";User ID=adminsanjose2;Password=Ag1c0l@18tz")]
        public string AGRICOLA2017ConnectionString {
            get {
                return ((string)(this["AGRICOLA2017ConnectionString"]));
            }
        }
    }
}
