#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportista.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="agricolasanjuan2014")]
	public partial class SJ_RHFacturacionTransportistaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertSJ_RHTransportistaChofer(SJ_RHTransportistaChofer instance);
    partial void UpdateSJ_RHTransportistaChofer(SJ_RHTransportistaChofer instance);
    partial void DeleteSJ_RHTransportistaChofer(SJ_RHTransportistaChofer instance);
    partial void InsertSJ_RHTransportistaContrato(SJ_RHTransportistaContrato instance);
    partial void UpdateSJ_RHTransportistaContrato(SJ_RHTransportistaContrato instance);
    partial void DeleteSJ_RHTransportistaContrato(SJ_RHTransportistaContrato instance);
    partial void InsertSJ_RHRuta(SJ_RHRuta instance);
    partial void UpdateSJ_RHRuta(SJ_RHRuta instance);
    partial void DeleteSJ_RHRuta(SJ_RHRuta instance);
    partial void InsertSJ_RHTransportistaRuta(SJ_RHTransportistaRuta instance);
    partial void UpdateSJ_RHTransportistaRuta(SJ_RHTransportistaRuta instance);
    partial void DeleteSJ_RHTransportistaRuta(SJ_RHTransportistaRuta instance);
    partial void InsertSJ_RHMovimientoMovilidad(SJ_RHMovimientoMovilidad instance);
    partial void UpdateSJ_RHMovimientoMovilidad(SJ_RHMovimientoMovilidad instance);
    partial void DeleteSJ_RHMovimientoMovilidad(SJ_RHMovimientoMovilidad instance);
    partial void InsertSJ_RHTransportista(SJ_RHTransportista instance);
    partial void UpdateSJ_RHTransportista(SJ_RHTransportista instance);
    partial void DeleteSJ_RHTransportista(SJ_RHTransportista instance);
    #endregion
		
		public SJ_RHFacturacionTransportistaDataContext() : 
				base(global::Transportista.Datos.Properties.Settings.Default.agricolasanjuan2014ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SJ_RHFacturacionTransportistaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SJ_RHFacturacionTransportistaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SJ_RHFacturacionTransportistaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SJ_RHFacturacionTransportistaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SJ_RHTransportistaChofer> SJ_RHTransportistaChofer
		{
			get
			{
				return this.GetTable<SJ_RHTransportistaChofer>();
			}
		}
		
		public System.Data.Linq.Table<SJ_RHTransportistaContrato> SJ_RHTransportistaContrato
		{
			get
			{
				return this.GetTable<SJ_RHTransportistaContrato>();
			}
		}
		
		public System.Data.Linq.Table<vSJ_RHListaUbigeo> vSJ_RHListaUbigeo
		{
			get
			{
				return this.GetTable<vSJ_RHListaUbigeo>();
			}
		}
		
		public System.Data.Linq.Table<SJ_RHRuta> SJ_RHRuta
		{
			get
			{
				return this.GetTable<SJ_RHRuta>();
			}
		}
		
		public System.Data.Linq.Table<SJ_RHTransportistaRuta> SJ_RHTransportistaRuta
		{
			get
			{
				return this.GetTable<SJ_RHTransportistaRuta>();
			}
		}
		
		public System.Data.Linq.Table<SJ_RHMovimientoMovilidad> SJ_RHMovimientoMovilidad
		{
			get
			{
				return this.GetTable<SJ_RHMovimientoMovilidad>();
			}
		}
		
		public System.Data.Linq.Table<SJ_RHTransportista> SJ_RHTransportista
		{
			get
			{
				return this.GetTable<SJ_RHTransportista>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListarDetalleTransportistaChofer")]
		public ISingleResult<SJ_RHListarDetalleTransportistaChoferResult> SJ_RHListarDetalleTransportistaChofer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SJ_RHListarDetalleTransportistaChoferResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListarDetalleTransportistaContrato")]
		public ISingleResult<SJ_RHListarDetalleTransportistaContratoResult> SJ_RHListarDetalleTransportistaContrato([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SJ_RHListarDetalleTransportistaContratoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHEliminarTransportista")]
		public int SJ_RHEliminarTransportista([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListaRutas")]
		public ISingleResult<SJ_RHListaRutasResult> SJ_RHListaRutas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SJ_RHListaRutasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListaUbigeo")]
		public ISingleResult<SJ_RHListaUbigeoResult> SJ_RHListaUbigeo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SJ_RHListaUbigeoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListarDetalleTransportistaRuta")]
		public ISingleResult<SJ_RHListarDetalleTransportistaRutaResult> SJ_RHListarDetalleTransportistaRuta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SJ_RHListarDetalleTransportistaRutaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerId")]
		public ISingleResult<ObtenerIdResult> ObtenerId()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHListarTransportistas")]
		public ISingleResult<SJ_RHListarTransportistasResult> SJ_RHListarTransportistas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SJ_RHListarTransportistasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajador")]
		public ISingleResult<SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajadorResult> SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dniPension, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dnitrabajador)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, dniPension, dnitrabajador);
			return ((ISingleResult<SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SJ_RHObtenerRefrigeriosRecibidosxDniTrabador")]
		public ISingleResult<SJ_RHObtenerRefrigeriosRecibidosxDniTrabadorResult> SJ_RHObtenerRefrigeriosRecibidosxDniTrabador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dniTrabajador, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dniTrabajador, desde, hasta);
			return ((ISingleResult<SJ_RHObtenerRefrigeriosRecibidosxDniTrabadorResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHTransportistaChofer")]
	public partial class SJ_RHTransportistaChofer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Item;
		
		private string _DNI;
		
		private string _Nombres;
		
		private string _TipoLicencia;
		
		private System.Nullable<byte> _EsCapacitado;
		
		private string _Observacion;
		
		private string _IdEstado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnTipoLicenciaChanging(string value);
    partial void OnTipoLicenciaChanged();
    partial void OnEsCapacitadoChanging(System.Nullable<byte> value);
    partial void OnEsCapacitadoChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    #endregion
		
		public SJ_RHTransportistaChofer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(200)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoLicencia", DbType="Char(20)")]
		public string TipoLicencia
		{
			get
			{
				return this._TipoLicencia;
			}
			set
			{
				if ((this._TipoLicencia != value))
				{
					this.OnTipoLicenciaChanging(value);
					this.SendPropertyChanging();
					this._TipoLicencia = value;
					this.SendPropertyChanged("TipoLicencia");
					this.OnTipoLicenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsCapacitado", DbType="TinyInt")]
		public System.Nullable<byte> EsCapacitado
		{
			get
			{
				return this._EsCapacitado;
			}
			set
			{
				if ((this._EsCapacitado != value))
				{
					this.OnEsCapacitadoChanging(value);
					this.SendPropertyChanging();
					this._EsCapacitado = value;
					this.SendPropertyChanged("EsCapacitado");
					this.OnEsCapacitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHTransportistaContrato")]
	public partial class SJ_RHTransportistaContrato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Item;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaTermino;
		
		private string _Observacion;
		
		private string _IdEstado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnFechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInicioChanged();
    partial void OnFechaTerminoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaTerminoChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    #endregion
		
		public SJ_RHTransportistaContrato()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaTermino", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaTermino
		{
			get
			{
				return this._FechaTermino;
			}
			set
			{
				if ((this._FechaTermino != value))
				{
					this.OnFechaTerminoChanging(value);
					this.SendPropertyChanging();
					this._FechaTermino = value;
					this.SendPropertyChanged("FechaTermino");
					this.OnFechaTerminoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vSJ_RHListaUbigeo")]
	public partial class vSJ_RHListaUbigeo
	{
		
		private string _Id;
		
		private string _Departamento;
		
		private string _Provincia;
		
		private string _Distrito;
		
		public vSJ_RHListaUbigeo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(6)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(25)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(25)")]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this._Provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="VarChar(25)")]
		public string Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this._Distrito = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHRuta")]
	public partial class SJ_RHRuta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _RutaOrigen;
		
		private string _RutaDestino;
		
		private System.Nullable<decimal> _Distancia;
		
		private System.Nullable<decimal> _TiempoViaje;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRutaOrigenChanging(string value);
    partial void OnRutaOrigenChanged();
    partial void OnRutaDestinoChanging(string value);
    partial void OnRutaDestinoChanged();
    partial void OnDistanciaChanging(System.Nullable<decimal> value);
    partial void OnDistanciaChanged();
    partial void OnTiempoViajeChanging(System.Nullable<decimal> value);
    partial void OnTiempoViajeChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    #endregion
		
		public SJ_RHRuta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaOrigen", DbType="Char(6)")]
		public string RutaOrigen
		{
			get
			{
				return this._RutaOrigen;
			}
			set
			{
				if ((this._RutaOrigen != value))
				{
					this.OnRutaOrigenChanging(value);
					this.SendPropertyChanging();
					this._RutaOrigen = value;
					this.SendPropertyChanged("RutaOrigen");
					this.OnRutaOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaDestino", DbType="Char(6)")]
		public string RutaDestino
		{
			get
			{
				return this._RutaDestino;
			}
			set
			{
				if ((this._RutaDestino != value))
				{
					this.OnRutaDestinoChanging(value);
					this.SendPropertyChanging();
					this._RutaDestino = value;
					this.SendPropertyChanged("RutaDestino");
					this.OnRutaDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distancia", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> Distancia
		{
			get
			{
				return this._Distancia;
			}
			set
			{
				if ((this._Distancia != value))
				{
					this.OnDistanciaChanging(value);
					this.SendPropertyChanging();
					this._Distancia = value;
					this.SendPropertyChanged("Distancia");
					this.OnDistanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoViaje", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> TiempoViaje
		{
			get
			{
				return this._TiempoViaje;
			}
			set
			{
				if ((this._TiempoViaje != value))
				{
					this.OnTiempoViajeChanging(value);
					this.SendPropertyChanging();
					this._TiempoViaje = value;
					this.SendPropertyChanged("TiempoViaje");
					this.OnTiempoViajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHTransportistaRuta")]
	public partial class SJ_RHTransportistaRuta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Item;
		
		private int _IdRuta;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private System.Nullable<decimal> _PrecioPersona;
		
		private System.Nullable<decimal> _PrecioFlete;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnIdRutaChanging(int value);
    partial void OnIdRutaChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    partial void OnPrecioPersonaChanging(System.Nullable<decimal> value);
    partial void OnPrecioPersonaChanged();
    partial void OnPrecioFleteChanging(System.Nullable<decimal> value);
    partial void OnPrecioFleteChanged();
    #endregion
		
		public SJ_RHTransportistaRuta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRuta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdRuta
		{
			get
			{
				return this._IdRuta;
			}
			set
			{
				if ((this._IdRuta != value))
				{
					this.OnIdRutaChanging(value);
					this.SendPropertyChanging();
					this._IdRuta = value;
					this.SendPropertyChanged("IdRuta");
					this.OnIdRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioPersona", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PrecioPersona
		{
			get
			{
				return this._PrecioPersona;
			}
			set
			{
				if ((this._PrecioPersona != value))
				{
					this.OnPrecioPersonaChanging(value);
					this.SendPropertyChanging();
					this._PrecioPersona = value;
					this.SendPropertyChanged("PrecioPersona");
					this.OnPrecioPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioFlete", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PrecioFlete
		{
			get
			{
				return this._PrecioFlete;
			}
			set
			{
				if ((this._PrecioFlete != value))
				{
					this.OnPrecioFleteChanging(value);
					this.SendPropertyChanging();
					this._PrecioFlete = value;
					this.SendPropertyChanged("PrecioFlete");
					this.OnPrecioFleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHMovimientoMovilidad")]
	public partial class SJ_RHMovimientoMovilidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private int _IdTransportista;
		
		private string _IdDocumento;
		
		private string _Serie;
		
		private string _Numero;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _NumeroManual;
		
		private string _IdEstado;
		
		private string _RegistroMovimiento;
		
		private System.Nullable<int> _IdRutaOrigen;
		
		private System.Nullable<int> _IdRutaDestino;
		
		private System.Nullable<int> _NumeroPersonas;
		
		private System.Nullable<decimal> _PrecioIda;
		
		private System.Nullable<decimal> _PrecioVuelta;
		
		private System.Nullable<decimal> _PrecioxPersonaIda;
		
		private System.Nullable<decimal> _PrecioxPersonaVuelva;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnIdTransportistaChanging(int value);
    partial void OnIdTransportistaChanged();
    partial void OnIdDocumentoChanging(string value);
    partial void OnIdDocumentoChanged();
    partial void OnSerieChanging(string value);
    partial void OnSerieChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnNumeroManualChanging(string value);
    partial void OnNumeroManualChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    partial void OnRegistroMovimientoChanging(string value);
    partial void OnRegistroMovimientoChanged();
    partial void OnIdRutaOrigenChanging(System.Nullable<int> value);
    partial void OnIdRutaOrigenChanged();
    partial void OnIdRutaDestinoChanging(System.Nullable<int> value);
    partial void OnIdRutaDestinoChanged();
    partial void OnNumeroPersonasChanging(System.Nullable<int> value);
    partial void OnNumeroPersonasChanged();
    partial void OnPrecioIdaChanging(System.Nullable<decimal> value);
    partial void OnPrecioIdaChanged();
    partial void OnPrecioVueltaChanging(System.Nullable<decimal> value);
    partial void OnPrecioVueltaChanged();
    partial void OnPrecioxPersonaIdaChanging(System.Nullable<decimal> value);
    partial void OnPrecioxPersonaIdaChanged();
    partial void OnPrecioxPersonaVuelvaChanging(System.Nullable<decimal> value);
    partial void OnPrecioxPersonaVuelvaChanged();
    #endregion
		
		public SJ_RHMovimientoMovilidad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTransportista", DbType="Int NOT NULL")]
		public int IdTransportista
		{
			get
			{
				return this._IdTransportista;
			}
			set
			{
				if ((this._IdTransportista != value))
				{
					this.OnIdTransportistaChanging(value);
					this.SendPropertyChanging();
					this._IdTransportista = value;
					this.SendPropertyChanged("IdTransportista");
					this.OnIdTransportistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDocumento", DbType="Char(3)")]
		public string IdDocumento
		{
			get
			{
				return this._IdDocumento;
			}
			set
			{
				if ((this._IdDocumento != value))
				{
					this.OnIdDocumentoChanging(value);
					this.SendPropertyChanging();
					this._IdDocumento = value;
					this.SendPropertyChanged("IdDocumento");
					this.OnIdDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="Char(4)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this.OnSerieChanging(value);
					this.SendPropertyChanging();
					this._Serie = value;
					this.SendPropertyChanged("Serie");
					this.OnSerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Char(7)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroManual", DbType="Char(7)")]
		public string NumeroManual
		{
			get
			{
				return this._NumeroManual;
			}
			set
			{
				if ((this._NumeroManual != value))
				{
					this.OnNumeroManualChanging(value);
					this.SendPropertyChanging();
					this._NumeroManual = value;
					this.SendPropertyChanged("NumeroManual");
					this.OnNumeroManualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroMovimiento", DbType="Char(2)")]
		public string RegistroMovimiento
		{
			get
			{
				return this._RegistroMovimiento;
			}
			set
			{
				if ((this._RegistroMovimiento != value))
				{
					this.OnRegistroMovimientoChanging(value);
					this.SendPropertyChanging();
					this._RegistroMovimiento = value;
					this.SendPropertyChanged("RegistroMovimiento");
					this.OnRegistroMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRutaOrigen", DbType="Int")]
		public System.Nullable<int> IdRutaOrigen
		{
			get
			{
				return this._IdRutaOrigen;
			}
			set
			{
				if ((this._IdRutaOrigen != value))
				{
					this.OnIdRutaOrigenChanging(value);
					this.SendPropertyChanging();
					this._IdRutaOrigen = value;
					this.SendPropertyChanged("IdRutaOrigen");
					this.OnIdRutaOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRutaDestino", DbType="Int")]
		public System.Nullable<int> IdRutaDestino
		{
			get
			{
				return this._IdRutaDestino;
			}
			set
			{
				if ((this._IdRutaDestino != value))
				{
					this.OnIdRutaDestinoChanging(value);
					this.SendPropertyChanging();
					this._IdRutaDestino = value;
					this.SendPropertyChanged("IdRutaDestino");
					this.OnIdRutaDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPersonas", DbType="Int")]
		public System.Nullable<int> NumeroPersonas
		{
			get
			{
				return this._NumeroPersonas;
			}
			set
			{
				if ((this._NumeroPersonas != value))
				{
					this.OnNumeroPersonasChanging(value);
					this.SendPropertyChanging();
					this._NumeroPersonas = value;
					this.SendPropertyChanged("NumeroPersonas");
					this.OnNumeroPersonasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioIda", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> PrecioIda
		{
			get
			{
				return this._PrecioIda;
			}
			set
			{
				if ((this._PrecioIda != value))
				{
					this.OnPrecioIdaChanging(value);
					this.SendPropertyChanging();
					this._PrecioIda = value;
					this.SendPropertyChanged("PrecioIda");
					this.OnPrecioIdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVuelta", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> PrecioVuelta
		{
			get
			{
				return this._PrecioVuelta;
			}
			set
			{
				if ((this._PrecioVuelta != value))
				{
					this.OnPrecioVueltaChanging(value);
					this.SendPropertyChanging();
					this._PrecioVuelta = value;
					this.SendPropertyChanged("PrecioVuelta");
					this.OnPrecioVueltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioxPersonaIda", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PrecioxPersonaIda
		{
			get
			{
				return this._PrecioxPersonaIda;
			}
			set
			{
				if ((this._PrecioxPersonaIda != value))
				{
					this.OnPrecioxPersonaIdaChanging(value);
					this.SendPropertyChanging();
					this._PrecioxPersonaIda = value;
					this.SendPropertyChanged("PrecioxPersonaIda");
					this.OnPrecioxPersonaIdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioxPersonaVuelva", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PrecioxPersonaVuelva
		{
			get
			{
				return this._PrecioxPersonaVuelva;
			}
			set
			{
				if ((this._PrecioxPersonaVuelva != value))
				{
					this.OnPrecioxPersonaVuelvaChanging(value);
					this.SendPropertyChanging();
					this._PrecioxPersonaVuelva = value;
					this.SendPropertyChanged("PrecioxPersonaVuelva");
					this.OnPrecioxPersonaVuelvaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJ_RHTransportista")]
	public partial class SJ_RHTransportista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _RUC;
		
		private string _Placa;
		
		private string _NombreCorto;
		
		private string _TipoMovilidad;
		
		private System.Nullable<int> _NumeroAsientos;
		
		private System.Nullable<decimal> _PesoMaximo;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private System.Nullable<byte> _EsMovilidadLocal;
		
		private System.Nullable<byte> _EsInterLocal;
		
		private string _AnioFabricacion;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _IdEstado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRUCChanging(string value);
    partial void OnRUCChanged();
    partial void OnPlacaChanging(string value);
    partial void OnPlacaChanged();
    partial void OnNombreCortoChanging(string value);
    partial void OnNombreCortoChanged();
    partial void OnTipoMovilidadChanging(string value);
    partial void OnTipoMovilidadChanged();
    partial void OnNumeroAsientosChanging(System.Nullable<int> value);
    partial void OnNumeroAsientosChanged();
    partial void OnPesoMaximoChanging(System.Nullable<decimal> value);
    partial void OnPesoMaximoChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnEsMovilidadLocalChanging(System.Nullable<byte> value);
    partial void OnEsMovilidadLocalChanged();
    partial void OnEsInterLocalChanging(System.Nullable<byte> value);
    partial void OnEsInterLocalChanged();
    partial void OnAnioFabricacionChanging(string value);
    partial void OnAnioFabricacionChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnIdEstadoChanging(string value);
    partial void OnIdEstadoChanged();
    #endregion
		
		public SJ_RHTransportista()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="Char(12)")]
		public string RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this.OnRUCChanging(value);
					this.SendPropertyChanging();
					this._RUC = value;
					this.SendPropertyChanged("RUC");
					this.OnRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="Char(30)")]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this.OnPlacaChanging(value);
					this.SendPropertyChanging();
					this._Placa = value;
					this.SendPropertyChanged("Placa");
					this.OnPlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCorto", DbType="Char(100)")]
		public string NombreCorto
		{
			get
			{
				return this._NombreCorto;
			}
			set
			{
				if ((this._NombreCorto != value))
				{
					this.OnNombreCortoChanging(value);
					this.SendPropertyChanging();
					this._NombreCorto = value;
					this.SendPropertyChanged("NombreCorto");
					this.OnNombreCortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMovilidad", DbType="Char(3)")]
		public string TipoMovilidad
		{
			get
			{
				return this._TipoMovilidad;
			}
			set
			{
				if ((this._TipoMovilidad != value))
				{
					this.OnTipoMovilidadChanging(value);
					this.SendPropertyChanging();
					this._TipoMovilidad = value;
					this.SendPropertyChanged("TipoMovilidad");
					this.OnTipoMovilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroAsientos", DbType="Int")]
		public System.Nullable<int> NumeroAsientos
		{
			get
			{
				return this._NumeroAsientos;
			}
			set
			{
				if ((this._NumeroAsientos != value))
				{
					this.OnNumeroAsientosChanging(value);
					this.SendPropertyChanging();
					this._NumeroAsientos = value;
					this.SendPropertyChanged("NumeroAsientos");
					this.OnNumeroAsientosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoMaximo", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PesoMaximo
		{
			get
			{
				return this._PesoMaximo;
			}
			set
			{
				if ((this._PesoMaximo != value))
				{
					this.OnPesoMaximoChanging(value);
					this.SendPropertyChanging();
					this._PesoMaximo = value;
					this.SendPropertyChanged("PesoMaximo");
					this.OnPesoMaximoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsMovilidadLocal", DbType="TinyInt")]
		public System.Nullable<byte> EsMovilidadLocal
		{
			get
			{
				return this._EsMovilidadLocal;
			}
			set
			{
				if ((this._EsMovilidadLocal != value))
				{
					this.OnEsMovilidadLocalChanging(value);
					this.SendPropertyChanging();
					this._EsMovilidadLocal = value;
					this.SendPropertyChanged("EsMovilidadLocal");
					this.OnEsMovilidadLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsInterLocal", DbType="TinyInt")]
		public System.Nullable<byte> EsInterLocal
		{
			get
			{
				return this._EsInterLocal;
			}
			set
			{
				if ((this._EsInterLocal != value))
				{
					this.OnEsInterLocalChanging(value);
					this.SendPropertyChanging();
					this._EsInterLocal = value;
					this.SendPropertyChanged("EsInterLocal");
					this.OnEsInterLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioFabricacion", DbType="Char(4)")]
		public string AnioFabricacion
		{
			get
			{
				return this._AnioFabricacion;
			}
			set
			{
				if ((this._AnioFabricacion != value))
				{
					this.OnAnioFabricacionChanging(value);
					this.SendPropertyChanging();
					this._AnioFabricacion = value;
					this.SendPropertyChanged("AnioFabricacion");
					this.OnAnioFabricacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(20)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(20)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SJ_RHListarDetalleTransportistaChoferResult
	{
		
		private System.Nullable<int> _Id;
		
		private string _ITEM;
		
		private string _DNI;
		
		private string _Nombre;
		
		private string _TipoLicencia;
		
		private System.Nullable<byte> _EsCapacitado;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private string _Estado;
		
		public SJ_RHListarDetalleTransportistaChoferResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM", DbType="Char(3)")]
		public string ITEM
		{
			get
			{
				return this._ITEM;
			}
			set
			{
				if ((this._ITEM != value))
				{
					this._ITEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(8)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoLicencia", DbType="VarChar(20)")]
		public string TipoLicencia
		{
			get
			{
				return this._TipoLicencia;
			}
			set
			{
				if ((this._TipoLicencia != value))
				{
					this._TipoLicencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsCapacitado", DbType="TinyInt")]
		public System.Nullable<byte> EsCapacitado
		{
			get
			{
				return this._EsCapacitado;
			}
			set
			{
				if ((this._EsCapacitado != value))
				{
					this._EsCapacitado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SJ_RHListarDetalleTransportistaContratoResult
	{
		
		private System.Nullable<int> _Id;
		
		private string _ITEM;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaTermino;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private string _Estado;
		
		public SJ_RHListarDetalleTransportistaContratoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM", DbType="Char(3)")]
		public string ITEM
		{
			get
			{
				return this._ITEM;
			}
			set
			{
				if ((this._ITEM != value))
				{
					this._ITEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaTermino", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaTermino
		{
			get
			{
				return this._FechaTermino;
			}
			set
			{
				if ((this._FechaTermino != value))
				{
					this._FechaTermino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SJ_RHListaRutasResult
	{
		
		private int _Id;
		
		private string _RutaOrigen;
		
		private string _DepartamentoOrigen;
		
		private string _ProvinciaOrigen;
		
		private string _DistritoOrigen;
		
		private string _RutaDestino;
		
		private string _DepartamentoDestino;
		
		private string _ProvinciaDestino;
		
		private string _DistritoDestino;
		
		private System.Nullable<decimal> _Distancia;
		
		private System.Nullable<decimal> _TiempoViaje;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private string _Estado;
		
		public SJ_RHListaRutasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaOrigen", DbType="VarChar(6)")]
		public string RutaOrigen
		{
			get
			{
				return this._RutaOrigen;
			}
			set
			{
				if ((this._RutaOrigen != value))
				{
					this._RutaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartamentoOrigen", DbType="VarChar(25)")]
		public string DepartamentoOrigen
		{
			get
			{
				return this._DepartamentoOrigen;
			}
			set
			{
				if ((this._DepartamentoOrigen != value))
				{
					this._DepartamentoOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaOrigen", DbType="VarChar(25)")]
		public string ProvinciaOrigen
		{
			get
			{
				return this._ProvinciaOrigen;
			}
			set
			{
				if ((this._ProvinciaOrigen != value))
				{
					this._ProvinciaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoOrigen", DbType="VarChar(25)")]
		public string DistritoOrigen
		{
			get
			{
				return this._DistritoOrigen;
			}
			set
			{
				if ((this._DistritoOrigen != value))
				{
					this._DistritoOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaDestino", DbType="VarChar(6)")]
		public string RutaDestino
		{
			get
			{
				return this._RutaDestino;
			}
			set
			{
				if ((this._RutaDestino != value))
				{
					this._RutaDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartamentoDestino", DbType="VarChar(25)")]
		public string DepartamentoDestino
		{
			get
			{
				return this._DepartamentoDestino;
			}
			set
			{
				if ((this._DepartamentoDestino != value))
				{
					this._DepartamentoDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinciaDestino", DbType="VarChar(25)")]
		public string ProvinciaDestino
		{
			get
			{
				return this._ProvinciaDestino;
			}
			set
			{
				if ((this._ProvinciaDestino != value))
				{
					this._ProvinciaDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistritoDestino", DbType="VarChar(25)")]
		public string DistritoDestino
		{
			get
			{
				return this._DistritoDestino;
			}
			set
			{
				if ((this._DistritoDestino != value))
				{
					this._DistritoDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distancia", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> Distancia
		{
			get
			{
				return this._Distancia;
			}
			set
			{
				if ((this._Distancia != value))
				{
					this._Distancia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoViaje", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> TiempoViaje
		{
			get
			{
				return this._TiempoViaje;
			}
			set
			{
				if ((this._TiempoViaje != value))
				{
					this._TiempoViaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="VarChar(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SJ_RHListaUbigeoResult
	{
		
		private string _Id;
		
		private string _Departamento;
		
		private string _Provincia;
		
		private string _Distrito;
		
		public SJ_RHListaUbigeoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(6)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(25)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(25)")]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this._Provincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distrito", DbType="VarChar(25)")]
		public string Distrito
		{
			get
			{
				return this._Distrito;
			}
			set
			{
				if ((this._Distrito != value))
				{
					this._Distrito = value;
				}
			}
		}
	}
	
	public partial class SJ_RHListarDetalleTransportistaRutaResult
	{
		
		private int _Id;
		
		private string _Item;
		
		private int _IdRuta;
		
		private System.Nullable<decimal> _PrecioPersona;
		
		private System.Nullable<decimal> _PrecioFlete;
		
		private string _Ruta;
		
		private string _Observacion;
		
		private string _IdEstado;
		
		private string _Estado;
		
		public SJ_RHListarDetalleTransportistaRutaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRuta", DbType="Int NOT NULL")]
		public int IdRuta
		{
			get
			{
				return this._IdRuta;
			}
			set
			{
				if ((this._IdRuta != value))
				{
					this._IdRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioPersona", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PrecioPersona
		{
			get
			{
				return this._PrecioPersona;
			}
			set
			{
				if ((this._PrecioPersona != value))
				{
					this._PrecioPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioFlete", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PrecioFlete
		{
			get
			{
				return this._PrecioFlete;
			}
			set
			{
				if ((this._PrecioFlete != value))
				{
					this._PrecioFlete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruta", DbType="VarChar(53)")]
		public string Ruta
		{
			get
			{
				return this._Ruta;
			}
			set
			{
				if ((this._Ruta != value))
				{
					this._Ruta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class ObtenerIdResult
	{
		
		private string _Codigo;
		
		public ObtenerIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
	}
	
	public partial class SJ_RHListarTransportistasResult
	{
		
		private int _Id;
		
		private string _RUC;
		
		private string _RazonSocial;
		
		private string _Placa;
		
		private string _PseudoNombre;
		
		private string _IdTipoMovilidad;
		
		private string _TipoMovilidad;
		
		private System.Nullable<int> _NumeroAsientos;
		
		private System.Nullable<decimal> _PesoMaximo;
		
		private System.Nullable<byte> _EsMovilidadLocal;
		
		private System.Nullable<byte> _EsInterLocal;
		
		private string _AnioFabricacion;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _IdEstado;
		
		private string _Estado;
		
		public SJ_RHListarTransportistasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="Char(12)")]
		public string RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this._RUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(200)")]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(30)")]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this._Placa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PseudoNombre", DbType="VarChar(100)")]
		public string PseudoNombre
		{
			get
			{
				return this._PseudoNombre;
			}
			set
			{
				if ((this._PseudoNombre != value))
				{
					this._PseudoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoMovilidad", DbType="VarChar(3)")]
		public string IdTipoMovilidad
		{
			get
			{
				return this._IdTipoMovilidad;
			}
			set
			{
				if ((this._IdTipoMovilidad != value))
				{
					this._IdTipoMovilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMovilidad", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TipoMovilidad
		{
			get
			{
				return this._TipoMovilidad;
			}
			set
			{
				if ((this._TipoMovilidad != value))
				{
					this._TipoMovilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroAsientos", DbType="Int")]
		public System.Nullable<int> NumeroAsientos
		{
			get
			{
				return this._NumeroAsientos;
			}
			set
			{
				if ((this._NumeroAsientos != value))
				{
					this._NumeroAsientos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoMaximo", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> PesoMaximo
		{
			get
			{
				return this._PesoMaximo;
			}
			set
			{
				if ((this._PesoMaximo != value))
				{
					this._PesoMaximo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsMovilidadLocal", DbType="TinyInt")]
		public System.Nullable<byte> EsMovilidadLocal
		{
			get
			{
				return this._EsMovilidadLocal;
			}
			set
			{
				if ((this._EsMovilidadLocal != value))
				{
					this._EsMovilidadLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsInterLocal", DbType="TinyInt")]
		public System.Nullable<byte> EsInterLocal
		{
			get
			{
				return this._EsInterLocal;
			}
			set
			{
				if ((this._EsInterLocal != value))
				{
					this._EsInterLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioFabricacion", DbType="Char(4)")]
		public string AnioFabricacion
		{
			get
			{
				return this._AnioFabricacion;
			}
			set
			{
				if ((this._AnioFabricacion != value))
				{
					this._AnioFabricacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(20)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(20)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this._Modelo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Char(2)")]
		public string IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajadorResult
	{
		
		private string _dia;
		
		private string _fecha;
		
		private string _NombresTrabajador;
		
		private string _NombresPension;
		
		private string _Asistencia;
		
		private System.Nullable<int> _idTipoComida;
		
		private string _tipoComida;
		
		public SJ_RHConsultarHistorialAsistenciaRefrigerioxTrabajadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia", DbType="NVarChar(30)")]
		public string dia
		{
			get
			{
				return this._dia;
			}
			set
			{
				if ((this._dia != value))
				{
					this._dia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Char(10)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombresTrabajador", DbType="VarChar(100)")]
		public string NombresTrabajador
		{
			get
			{
				return this._NombresTrabajador;
			}
			set
			{
				if ((this._NombresTrabajador != value))
				{
					this._NombresTrabajador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombresPension", DbType="VarChar(100)")]
		public string NombresPension
		{
			get
			{
				return this._NombresPension;
			}
			set
			{
				if ((this._NombresPension != value))
				{
					this._NombresPension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asistencia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Asistencia
		{
			get
			{
				return this._Asistencia;
			}
			set
			{
				if ((this._Asistencia != value))
				{
					this._Asistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoComida", DbType="Int")]
		public System.Nullable<int> idTipoComida
		{
			get
			{
				return this._idTipoComida;
			}
			set
			{
				if ((this._idTipoComida != value))
				{
					this._idTipoComida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoComida", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string tipoComida
		{
			get
			{
				return this._tipoComida;
			}
			set
			{
				if ((this._tipoComida != value))
				{
					this._tipoComida = value;
				}
			}
		}
	}
	
	public partial class SJ_RHObtenerRefrigeriosRecibidosxDniTrabadorResult
	{
		
		private System.Nullable<System.DateTime> _fechaRefrigerio;
		
		private string _pension;
		
		private string _trabajador;
		
		private string _refrigerio;
		
		public SJ_RHObtenerRefrigeriosRecibidosxDniTrabadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRefrigerio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaRefrigerio
		{
			get
			{
				return this._fechaRefrigerio;
			}
			set
			{
				if ((this._fechaRefrigerio != value))
				{
					this._fechaRefrigerio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pension", DbType="VarChar(100)")]
		public string pension
		{
			get
			{
				return this._pension;
			}
			set
			{
				if ((this._pension != value))
				{
					this._pension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trabajador", DbType="VarChar(100)")]
		public string trabajador
		{
			get
			{
				return this._trabajador;
			}
			set
			{
				if ((this._trabajador != value))
				{
					this._trabajador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refrigerio", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string refrigerio
		{
			get
			{
				return this._refrigerio;
			}
			set
			{
				if ((this._refrigerio != value))
				{
					this._refrigerio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
