#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="saturno")]
	public partial class BDVISUALSATDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTractoLabor(TractoLabor instance);
    partial void UpdateTractoLabor(TractoLabor instance);
    partial void DeleteTractoLabor(TractoLabor instance);
    #endregion
		
		public BDVISUALSATDataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.saturnoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDVISUALSATDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVISUALSATDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVISUALSATDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVISUALSATDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TractoLabor> TractoLabor
		{
			get
			{
				return this.GetTable<TractoLabor>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoHorasDeTractorPorSemana")]
		public ISingleResult<SAS_ListadoHorasDeTractorPorSemanaResult> SAS_ListadoHorasDeTractorPorSemana([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string semana)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta, periodo, semana);
			return ((ISingleResult<SAS_ListadoHorasDeTractorPorSemanaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TractoLabor")]
	public partial class TractoLabor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _Turn;
		
		private string _Tracto;
		
		private System.Nullable<int> _Available;
		
		private System.Nullable<int> _IsLabor;
		
		private System.Nullable<decimal> _TimeTotal;
		
		private string _TimeTotalTx;
		
		private System.Nullable<decimal> _AreaTotal;
		
		private string _AreaTotalTx;
		
		private System.Nullable<double> _PerUse;
		
		private string _PerUseTx;
		
		private System.Nullable<decimal> _ElapsedTotal;
		
		private string _ElapsedTotalTx;
		
		private System.Nullable<decimal> _ElapsedTotalLote;
		
		private string _ElapsedTotalLoteTx;
		
		private System.Nullable<decimal> _ElapsedOutLote;
		
		private string _ElapsedOutLoteTx;
		
		private System.Nullable<decimal> _Advance;
		
		private System.Nullable<decimal> _AdvanceVal1;
		
		private System.Nullable<decimal> _AdvanceVal2;
		
		private System.Nullable<decimal> _Efficiendy;
		
		private System.Nullable<decimal> _EfficiendyVal1;
		
		private System.Nullable<decimal> _EfficiendyVal2;
		
		private System.Nullable<int> _nStop;
		
		private System.Nullable<decimal> _StopTime;
		
		private string _StopTimeTx;
		
		private System.Nullable<int> _SpeedAvgLote;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTurnChanging(System.Nullable<int> value);
    partial void OnTurnChanged();
    partial void OnTractoChanging(string value);
    partial void OnTractoChanged();
    partial void OnAvailableChanging(System.Nullable<int> value);
    partial void OnAvailableChanged();
    partial void OnIsLaborChanging(System.Nullable<int> value);
    partial void OnIsLaborChanged();
    partial void OnTimeTotalChanging(System.Nullable<decimal> value);
    partial void OnTimeTotalChanged();
    partial void OnTimeTotalTxChanging(string value);
    partial void OnTimeTotalTxChanged();
    partial void OnAreaTotalChanging(System.Nullable<decimal> value);
    partial void OnAreaTotalChanged();
    partial void OnAreaTotalTxChanging(string value);
    partial void OnAreaTotalTxChanged();
    partial void OnPerUseChanging(System.Nullable<double> value);
    partial void OnPerUseChanged();
    partial void OnPerUseTxChanging(string value);
    partial void OnPerUseTxChanged();
    partial void OnElapsedTotalChanging(System.Nullable<decimal> value);
    partial void OnElapsedTotalChanged();
    partial void OnElapsedTotalTxChanging(string value);
    partial void OnElapsedTotalTxChanged();
    partial void OnElapsedTotalLoteChanging(System.Nullable<decimal> value);
    partial void OnElapsedTotalLoteChanged();
    partial void OnElapsedTotalLoteTxChanging(string value);
    partial void OnElapsedTotalLoteTxChanged();
    partial void OnElapsedOutLoteChanging(System.Nullable<decimal> value);
    partial void OnElapsedOutLoteChanged();
    partial void OnElapsedOutLoteTxChanging(string value);
    partial void OnElapsedOutLoteTxChanged();
    partial void OnAdvanceChanging(System.Nullable<decimal> value);
    partial void OnAdvanceChanged();
    partial void OnAdvanceVal1Changing(System.Nullable<decimal> value);
    partial void OnAdvanceVal1Changed();
    partial void OnAdvanceVal2Changing(System.Nullable<decimal> value);
    partial void OnAdvanceVal2Changed();
    partial void OnEfficiendyChanging(System.Nullable<decimal> value);
    partial void OnEfficiendyChanged();
    partial void OnEfficiendyVal1Changing(System.Nullable<decimal> value);
    partial void OnEfficiendyVal1Changed();
    partial void OnEfficiendyVal2Changing(System.Nullable<decimal> value);
    partial void OnEfficiendyVal2Changed();
    partial void OnnStopChanging(System.Nullable<int> value);
    partial void OnnStopChanged();
    partial void OnStopTimeChanging(System.Nullable<decimal> value);
    partial void OnStopTimeChanged();
    partial void OnStopTimeTxChanging(string value);
    partial void OnStopTimeTxChanged();
    partial void OnSpeedAvgLoteChanging(System.Nullable<int> value);
    partial void OnSpeedAvgLoteChanged();
    #endregion
		
		public TractoLabor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turn", DbType="Int")]
		public System.Nullable<int> Turn
		{
			get
			{
				return this._Turn;
			}
			set
			{
				if ((this._Turn != value))
				{
					this.OnTurnChanging(value);
					this.SendPropertyChanging();
					this._Turn = value;
					this.SendPropertyChanged("Turn");
					this.OnTurnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tracto", DbType="VarChar(20)")]
		public string Tracto
		{
			get
			{
				return this._Tracto;
			}
			set
			{
				if ((this._Tracto != value))
				{
					this.OnTractoChanging(value);
					this.SendPropertyChanging();
					this._Tracto = value;
					this.SendPropertyChanged("Tracto");
					this.OnTractoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Int")]
		public System.Nullable<int> Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this.OnAvailableChanging(value);
					this.SendPropertyChanging();
					this._Available = value;
					this.SendPropertyChanged("Available");
					this.OnAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLabor", DbType="Int")]
		public System.Nullable<int> IsLabor
		{
			get
			{
				return this._IsLabor;
			}
			set
			{
				if ((this._IsLabor != value))
				{
					this.OnIsLaborChanging(value);
					this.SendPropertyChanging();
					this._IsLabor = value;
					this.SendPropertyChanged("IsLabor");
					this.OnIsLaborChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TimeTotal
		{
			get
			{
				return this._TimeTotal;
			}
			set
			{
				if ((this._TimeTotal != value))
				{
					this.OnTimeTotalChanging(value);
					this.SendPropertyChanging();
					this._TimeTotal = value;
					this.SendPropertyChanged("TimeTotal");
					this.OnTimeTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeTotalTx", DbType="VarChar(10)")]
		public string TimeTotalTx
		{
			get
			{
				return this._TimeTotalTx;
			}
			set
			{
				if ((this._TimeTotalTx != value))
				{
					this.OnTimeTotalTxChanging(value);
					this.SendPropertyChanging();
					this._TimeTotalTx = value;
					this.SendPropertyChanged("TimeTotalTx");
					this.OnTimeTotalTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AreaTotal
		{
			get
			{
				return this._AreaTotal;
			}
			set
			{
				if ((this._AreaTotal != value))
				{
					this.OnAreaTotalChanging(value);
					this.SendPropertyChanging();
					this._AreaTotal = value;
					this.SendPropertyChanged("AreaTotal");
					this.OnAreaTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaTotalTx", DbType="VarChar(10)")]
		public string AreaTotalTx
		{
			get
			{
				return this._AreaTotalTx;
			}
			set
			{
				if ((this._AreaTotalTx != value))
				{
					this.OnAreaTotalTxChanging(value);
					this.SendPropertyChanging();
					this._AreaTotalTx = value;
					this.SendPropertyChanged("AreaTotalTx");
					this.OnAreaTotalTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerUse", DbType="Float")]
		public System.Nullable<double> PerUse
		{
			get
			{
				return this._PerUse;
			}
			set
			{
				if ((this._PerUse != value))
				{
					this.OnPerUseChanging(value);
					this.SendPropertyChanging();
					this._PerUse = value;
					this.SendPropertyChanged("PerUse");
					this.OnPerUseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerUseTx", DbType="VarChar(4)")]
		public string PerUseTx
		{
			get
			{
				return this._PerUseTx;
			}
			set
			{
				if ((this._PerUseTx != value))
				{
					this.OnPerUseTxChanging(value);
					this.SendPropertyChanging();
					this._PerUseTx = value;
					this.SendPropertyChanged("PerUseTx");
					this.OnPerUseTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ElapsedTotal
		{
			get
			{
				return this._ElapsedTotal;
			}
			set
			{
				if ((this._ElapsedTotal != value))
				{
					this.OnElapsedTotalChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTotal = value;
					this.SendPropertyChanged("ElapsedTotal");
					this.OnElapsedTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTotalTx", DbType="VarChar(30)")]
		public string ElapsedTotalTx
		{
			get
			{
				return this._ElapsedTotalTx;
			}
			set
			{
				if ((this._ElapsedTotalTx != value))
				{
					this.OnElapsedTotalTxChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTotalTx = value;
					this.SendPropertyChanged("ElapsedTotalTx");
					this.OnElapsedTotalTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTotalLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ElapsedTotalLote
		{
			get
			{
				return this._ElapsedTotalLote;
			}
			set
			{
				if ((this._ElapsedTotalLote != value))
				{
					this.OnElapsedTotalLoteChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTotalLote = value;
					this.SendPropertyChanged("ElapsedTotalLote");
					this.OnElapsedTotalLoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTotalLoteTx", DbType="VarChar(30)")]
		public string ElapsedTotalLoteTx
		{
			get
			{
				return this._ElapsedTotalLoteTx;
			}
			set
			{
				if ((this._ElapsedTotalLoteTx != value))
				{
					this.OnElapsedTotalLoteTxChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTotalLoteTx = value;
					this.SendPropertyChanged("ElapsedTotalLoteTx");
					this.OnElapsedTotalLoteTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedOutLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ElapsedOutLote
		{
			get
			{
				return this._ElapsedOutLote;
			}
			set
			{
				if ((this._ElapsedOutLote != value))
				{
					this.OnElapsedOutLoteChanging(value);
					this.SendPropertyChanging();
					this._ElapsedOutLote = value;
					this.SendPropertyChanged("ElapsedOutLote");
					this.OnElapsedOutLoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedOutLoteTx", DbType="VarChar(30)")]
		public string ElapsedOutLoteTx
		{
			get
			{
				return this._ElapsedOutLoteTx;
			}
			set
			{
				if ((this._ElapsedOutLoteTx != value))
				{
					this.OnElapsedOutLoteTxChanging(value);
					this.SendPropertyChanging();
					this._ElapsedOutLoteTx = value;
					this.SendPropertyChanged("ElapsedOutLoteTx");
					this.OnElapsedOutLoteTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Advance
		{
			get
			{
				return this._Advance;
			}
			set
			{
				if ((this._Advance != value))
				{
					this.OnAdvanceChanging(value);
					this.SendPropertyChanging();
					this._Advance = value;
					this.SendPropertyChanged("Advance");
					this.OnAdvanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceVal1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AdvanceVal1
		{
			get
			{
				return this._AdvanceVal1;
			}
			set
			{
				if ((this._AdvanceVal1 != value))
				{
					this.OnAdvanceVal1Changing(value);
					this.SendPropertyChanging();
					this._AdvanceVal1 = value;
					this.SendPropertyChanged("AdvanceVal1");
					this.OnAdvanceVal1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvanceVal2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AdvanceVal2
		{
			get
			{
				return this._AdvanceVal2;
			}
			set
			{
				if ((this._AdvanceVal2 != value))
				{
					this.OnAdvanceVal2Changing(value);
					this.SendPropertyChanging();
					this._AdvanceVal2 = value;
					this.SendPropertyChanged("AdvanceVal2");
					this.OnAdvanceVal2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efficiendy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Efficiendy
		{
			get
			{
				return this._Efficiendy;
			}
			set
			{
				if ((this._Efficiendy != value))
				{
					this.OnEfficiendyChanging(value);
					this.SendPropertyChanging();
					this._Efficiendy = value;
					this.SendPropertyChanged("Efficiendy");
					this.OnEfficiendyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EfficiendyVal1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EfficiendyVal1
		{
			get
			{
				return this._EfficiendyVal1;
			}
			set
			{
				if ((this._EfficiendyVal1 != value))
				{
					this.OnEfficiendyVal1Changing(value);
					this.SendPropertyChanging();
					this._EfficiendyVal1 = value;
					this.SendPropertyChanged("EfficiendyVal1");
					this.OnEfficiendyVal1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EfficiendyVal2", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EfficiendyVal2
		{
			get
			{
				return this._EfficiendyVal2;
			}
			set
			{
				if ((this._EfficiendyVal2 != value))
				{
					this.OnEfficiendyVal2Changing(value);
					this.SendPropertyChanging();
					this._EfficiendyVal2 = value;
					this.SendPropertyChanged("EfficiendyVal2");
					this.OnEfficiendyVal2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nStop", DbType="Int")]
		public System.Nullable<int> nStop
		{
			get
			{
				return this._nStop;
			}
			set
			{
				if ((this._nStop != value))
				{
					this.OnnStopChanging(value);
					this.SendPropertyChanging();
					this._nStop = value;
					this.SendPropertyChanged("nStop");
					this.OnnStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopTime", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> StopTime
		{
			get
			{
				return this._StopTime;
			}
			set
			{
				if ((this._StopTime != value))
				{
					this.OnStopTimeChanging(value);
					this.SendPropertyChanging();
					this._StopTime = value;
					this.SendPropertyChanged("StopTime");
					this.OnStopTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StopTimeTx", DbType="VarChar(30)")]
		public string StopTimeTx
		{
			get
			{
				return this._StopTimeTx;
			}
			set
			{
				if ((this._StopTimeTx != value))
				{
					this.OnStopTimeTxChanging(value);
					this.SendPropertyChanging();
					this._StopTimeTx = value;
					this.SendPropertyChanged("StopTimeTx");
					this.OnStopTimeTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpeedAvgLote", DbType="Int")]
		public System.Nullable<int> SpeedAvgLote
		{
			get
			{
				return this._SpeedAvgLote;
			}
			set
			{
				if ((this._SpeedAvgLote != value))
				{
					this.OnSpeedAvgLoteChanging(value);
					this.SendPropertyChanging();
					this._SpeedAvgLote = value;
					this.SendPropertyChanged("SpeedAvgLote");
					this.OnSpeedAvgLoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SAS_ListadoHorasDeTractorPorSemanaResult
	{
		
		private int _codigoOperacion;
		
		private System.Nullable<System.DateTime> _fechaFormatoTexto;
		
		private System.Nullable<int> _turno;
		
		private string _turnoTrabajo;
		
		private string _turnoTrabajo2;
		
		private string _turnoTrabajo03;
		
		private System.Nullable<int> _disponibilidad;
		
		private string _TieneDisponibilidad;
		
		private System.Nullable<int> _siTieneProgramacionTrabajo;
		
		private string _ProgramacionDeLabores;
		
		private System.Nullable<decimal> _totalMinutos;
		
		private System.Nullable<decimal> _horasTrabajadas;
		
		private string _hrsTrabTX;
		
		private string _hrsTrabTX2;
		
		private System.Nullable<decimal> _minutosEnLote;
		
		private System.Nullable<decimal> _horasTrabajadasLote;
		
		private string _hrsTrabEnLoteTX;
		
		private string _hrsTrabEnLoteTX2;
		
		private System.Nullable<double> _procentajeEnLote;
		
		private string _procentajeEnLoteTX;
		
		private System.Nullable<decimal> _kilometrosRecorridosTotal;
		
		private string _kilometrosRecorridosTotalTx;
		
		private System.Nullable<decimal> _kilometrosRecorridosTotalEnLote;
		
		private string _kilometrosRecorridosTotalEnLoteTx;
		
		private System.Nullable<decimal> _Avance_KMxTurno;
		
		private System.Nullable<decimal> _minutosEnLote1;
		
		private System.Nullable<decimal> _HorasxTurnoDeTrabajo;
		
		private System.Nullable<decimal> _RendimientoKmEnLote;
		
		private System.Nullable<decimal> _KmRecorridosEnLote;
		
		private System.Nullable<decimal> _HorasRecorridosEnLote;
		
		private System.Nullable<int> _totalParadas;
		
		private System.Nullable<decimal> _TotalMinParados;
		
		private string _TotalMinParadosTx;
		
		private System.Nullable<int> _velocidadPromedio;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _año;
		
		private System.Nullable<int> _trimestre;
		
		private System.Nullable<int> _semana;
		
		private System.Nullable<int> _nroMes;
		
		private string _nombreMes;
		
		private System.Nullable<int> _diaDeSemana;
		
		private string _NombreDiaSemana;
		
		private System.Nullable<int> _nroDiaDelAnio;
		
		private System.Nullable<int> _dia;
		
		private System.Nullable<int> _mes;
		
		private System.Nullable<int> _anio;
		
		private string _tracto;
		
		public SAS_ListadoHorasDeTractorPorSemanaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoOperacion", DbType="Int NOT NULL")]
		public int codigoOperacion
		{
			get
			{
				return this._codigoOperacion;
			}
			set
			{
				if ((this._codigoOperacion != value))
				{
					this._codigoOperacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFormatoTexto", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFormatoTexto
		{
			get
			{
				return this._fechaFormatoTexto;
			}
			set
			{
				if ((this._fechaFormatoTexto != value))
				{
					this._fechaFormatoTexto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno", DbType="Int")]
		public System.Nullable<int> turno
		{
			get
			{
				return this._turno;
			}
			set
			{
				if ((this._turno != value))
				{
					this._turno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turnoTrabajo", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string turnoTrabajo
		{
			get
			{
				return this._turnoTrabajo;
			}
			set
			{
				if ((this._turnoTrabajo != value))
				{
					this._turnoTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turnoTrabajo2", DbType="VarChar(8)")]
		public string turnoTrabajo2
		{
			get
			{
				return this._turnoTrabajo2;
			}
			set
			{
				if ((this._turnoTrabajo2 != value))
				{
					this._turnoTrabajo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turnoTrabajo03", DbType="VarChar(8)")]
		public string turnoTrabajo03
		{
			get
			{
				return this._turnoTrabajo03;
			}
			set
			{
				if ((this._turnoTrabajo03 != value))
				{
					this._turnoTrabajo03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disponibilidad", DbType="Int")]
		public System.Nullable<int> disponibilidad
		{
			get
			{
				return this._disponibilidad;
			}
			set
			{
				if ((this._disponibilidad != value))
				{
					this._disponibilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieneDisponibilidad", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string TieneDisponibilidad
		{
			get
			{
				return this._TieneDisponibilidad;
			}
			set
			{
				if ((this._TieneDisponibilidad != value))
				{
					this._TieneDisponibilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siTieneProgramacionTrabajo", DbType="Int")]
		public System.Nullable<int> siTieneProgramacionTrabajo
		{
			get
			{
				return this._siTieneProgramacionTrabajo;
			}
			set
			{
				if ((this._siTieneProgramacionTrabajo != value))
				{
					this._siTieneProgramacionTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramacionDeLabores", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ProgramacionDeLabores
		{
			get
			{
				return this._ProgramacionDeLabores;
			}
			set
			{
				if ((this._ProgramacionDeLabores != value))
				{
					this._ProgramacionDeLabores = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalMinutos", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> totalMinutos
		{
			get
			{
				return this._totalMinutos;
			}
			set
			{
				if ((this._totalMinutos != value))
				{
					this._totalMinutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horasTrabajadas", DbType="Decimal(22,6)")]
		public System.Nullable<decimal> horasTrabajadas
		{
			get
			{
				return this._horasTrabajadas;
			}
			set
			{
				if ((this._horasTrabajadas != value))
				{
					this._horasTrabajadas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrsTrabTX", DbType="VarChar(10)")]
		public string hrsTrabTX
		{
			get
			{
				return this._hrsTrabTX;
			}
			set
			{
				if ((this._hrsTrabTX != value))
				{
					this._hrsTrabTX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrsTrabTX2", DbType="VarChar(8000)")]
		public string hrsTrabTX2
		{
			get
			{
				return this._hrsTrabTX2;
			}
			set
			{
				if ((this._hrsTrabTX2 != value))
				{
					this._hrsTrabTX2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minutosEnLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> minutosEnLote
		{
			get
			{
				return this._minutosEnLote;
			}
			set
			{
				if ((this._minutosEnLote != value))
				{
					this._minutosEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horasTrabajadasLote", DbType="Decimal(22,6)")]
		public System.Nullable<decimal> horasTrabajadasLote
		{
			get
			{
				return this._horasTrabajadasLote;
			}
			set
			{
				if ((this._horasTrabajadasLote != value))
				{
					this._horasTrabajadasLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrsTrabEnLoteTX", DbType="VarChar(10)")]
		public string hrsTrabEnLoteTX
		{
			get
			{
				return this._hrsTrabEnLoteTX;
			}
			set
			{
				if ((this._hrsTrabEnLoteTX != value))
				{
					this._hrsTrabEnLoteTX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrsTrabEnLoteTX2", DbType="VarChar(8000)")]
		public string hrsTrabEnLoteTX2
		{
			get
			{
				return this._hrsTrabEnLoteTX2;
			}
			set
			{
				if ((this._hrsTrabEnLoteTX2 != value))
				{
					this._hrsTrabEnLoteTX2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procentajeEnLote", DbType="Float")]
		public System.Nullable<double> procentajeEnLote
		{
			get
			{
				return this._procentajeEnLote;
			}
			set
			{
				if ((this._procentajeEnLote != value))
				{
					this._procentajeEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procentajeEnLoteTX", DbType="VarChar(4)")]
		public string procentajeEnLoteTX
		{
			get
			{
				return this._procentajeEnLoteTX;
			}
			set
			{
				if ((this._procentajeEnLoteTX != value))
				{
					this._procentajeEnLoteTX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilometrosRecorridosTotal", DbType="Decimal(23,7)")]
		public System.Nullable<decimal> kilometrosRecorridosTotal
		{
			get
			{
				return this._kilometrosRecorridosTotal;
			}
			set
			{
				if ((this._kilometrosRecorridosTotal != value))
				{
					this._kilometrosRecorridosTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilometrosRecorridosTotalTx", DbType="VarChar(30)")]
		public string kilometrosRecorridosTotalTx
		{
			get
			{
				return this._kilometrosRecorridosTotalTx;
			}
			set
			{
				if ((this._kilometrosRecorridosTotalTx != value))
				{
					this._kilometrosRecorridosTotalTx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilometrosRecorridosTotalEnLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> kilometrosRecorridosTotalEnLote
		{
			get
			{
				return this._kilometrosRecorridosTotalEnLote;
			}
			set
			{
				if ((this._kilometrosRecorridosTotalEnLote != value))
				{
					this._kilometrosRecorridosTotalEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilometrosRecorridosTotalEnLoteTx", DbType="VarChar(30)")]
		public string kilometrosRecorridosTotalEnLoteTx
		{
			get
			{
				return this._kilometrosRecorridosTotalEnLoteTx;
			}
			set
			{
				if ((this._kilometrosRecorridosTotalEnLoteTx != value))
				{
					this._kilometrosRecorridosTotalEnLoteTx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avance_KMxTurno", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Avance_KMxTurno
		{
			get
			{
				return this._Avance_KMxTurno;
			}
			set
			{
				if ((this._Avance_KMxTurno != value))
				{
					this._Avance_KMxTurno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minutosEnLote1", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> minutosEnLote1
		{
			get
			{
				return this._minutosEnLote1;
			}
			set
			{
				if ((this._minutosEnLote1 != value))
				{
					this._minutosEnLote1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasxTurnoDeTrabajo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HorasxTurnoDeTrabajo
		{
			get
			{
				return this._HorasxTurnoDeTrabajo;
			}
			set
			{
				if ((this._HorasxTurnoDeTrabajo != value))
				{
					this._HorasxTurnoDeTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RendimientoKmEnLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RendimientoKmEnLote
		{
			get
			{
				return this._RendimientoKmEnLote;
			}
			set
			{
				if ((this._RendimientoKmEnLote != value))
				{
					this._RendimientoKmEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KmRecorridosEnLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> KmRecorridosEnLote
		{
			get
			{
				return this._KmRecorridosEnLote;
			}
			set
			{
				if ((this._KmRecorridosEnLote != value))
				{
					this._KmRecorridosEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasRecorridosEnLote", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HorasRecorridosEnLote
		{
			get
			{
				return this._HorasRecorridosEnLote;
			}
			set
			{
				if ((this._HorasRecorridosEnLote != value))
				{
					this._HorasRecorridosEnLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalParadas", DbType="Int")]
		public System.Nullable<int> totalParadas
		{
			get
			{
				return this._totalParadas;
			}
			set
			{
				if ((this._totalParadas != value))
				{
					this._totalParadas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMinParados", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalMinParados
		{
			get
			{
				return this._TotalMinParados;
			}
			set
			{
				if ((this._TotalMinParados != value))
				{
					this._TotalMinParados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMinParadosTx", DbType="VarChar(30)")]
		public string TotalMinParadosTx
		{
			get
			{
				return this._TotalMinParadosTx;
			}
			set
			{
				if ((this._TotalMinParadosTx != value))
				{
					this._TotalMinParadosTx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_velocidadPromedio", DbType="Int")]
		public System.Nullable<int> velocidadPromedio
		{
			get
			{
				return this._velocidadPromedio;
			}
			set
			{
				if ((this._velocidadPromedio != value))
				{
					this._velocidadPromedio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_año", DbType="Int")]
		public System.Nullable<int> año
		{
			get
			{
				return this._año;
			}
			set
			{
				if ((this._año != value))
				{
					this._año = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trimestre", DbType="Int")]
		public System.Nullable<int> trimestre
		{
			get
			{
				return this._trimestre;
			}
			set
			{
				if ((this._trimestre != value))
				{
					this._trimestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semana", DbType="Int")]
		public System.Nullable<int> semana
		{
			get
			{
				return this._semana;
			}
			set
			{
				if ((this._semana != value))
				{
					this._semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroMes", DbType="Int")]
		public System.Nullable<int> nroMes
		{
			get
			{
				return this._nroMes;
			}
			set
			{
				if ((this._nroMes != value))
				{
					this._nroMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMes", DbType="NVarChar(30)")]
		public string nombreMes
		{
			get
			{
				return this._nombreMes;
			}
			set
			{
				if ((this._nombreMes != value))
				{
					this._nombreMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDeSemana", DbType="Int")]
		public System.Nullable<int> diaDeSemana
		{
			get
			{
				return this._diaDeSemana;
			}
			set
			{
				if ((this._diaDeSemana != value))
				{
					this._diaDeSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDiaSemana", DbType="NVarChar(30)")]
		public string NombreDiaSemana
		{
			get
			{
				return this._NombreDiaSemana;
			}
			set
			{
				if ((this._NombreDiaSemana != value))
				{
					this._NombreDiaSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDiaDelAnio", DbType="Int")]
		public System.Nullable<int> nroDiaDelAnio
		{
			get
			{
				return this._nroDiaDelAnio;
			}
			set
			{
				if ((this._nroDiaDelAnio != value))
				{
					this._nroDiaDelAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia", DbType="Int")]
		public System.Nullable<int> dia
		{
			get
			{
				return this._dia;
			}
			set
			{
				if ((this._dia != value))
				{
					this._dia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="Int")]
		public System.Nullable<int> mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this._mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this._anio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tracto", DbType="VarChar(20)")]
		public string tracto
		{
			get
			{
				return this._tracto;
			}
			set
			{
				if ((this._tracto != value))
				{
					this._tracto = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
