#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDO")]
	public partial class DBBDODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTractorVS(TractorVS instance);
    partial void UpdateTractorVS(TractorVS instance);
    partial void DeleteTractorVS(TractorVS instance);
    partial void InsertSemana(Semana instance);
    partial void UpdateSemana(Semana instance);
    partial void DeleteSemana(Semana instance);
    #endregion
		
		public DBBDODataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.BDOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBBDODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBDODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBDODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBDODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TractorVS> TractorVS
		{
			get
			{
				return this.GetTable<TractorVS>();
			}
		}
		
		public System.Data.Linq.Table<Semana> Semana
		{
			get
			{
				return this.GetTable<Semana>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoPartesDeMaquinariaPorSemana")]
		public ISingleResult<SAS_ListadoPartesDeMaquinariaPorSemanaResult> SAS_ListadoPartesDeMaquinariaPorSemana([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string semana)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta, periodo, semana);
			return ((ISingleResult<SAS_ListadoPartesDeMaquinariaPorSemanaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoCombustibleAbastecidosATractorPorSemana")]
		public ISingleResult<SAS_ListadoCombustibleAbastecidosATractorPorSemanaResult> SAS_ListadoCombustibleAbastecidosATractorPorSemana([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string semana)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta, periodo, semana);
			return ((ISingleResult<SAS_ListadoCombustibleAbastecidosATractorPorSemanaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ActualizarTransferenciaDeInformacion")]
		public int SAS_ActualizarTransferenciaDeInformacion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoFiltroReporteVisualSAT_NISIRA")]
		public ISingleResult<SAS_ListadoFiltroReporteVisualSAT_NISIRAResult> SAS_ListadoFiltroReporteVisualSAT_NISIRA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SAS_ListadoFiltroReporteVisualSAT_NISIRAResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TractorVS")]
	public partial class TractorVS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _idConsumidor;
		
		private string _tractorImplemento;
		
		private string _PropioAlquilado;
		
		private string _estado;
		
		private string _linea;
		
		private string _cultivo;
		
		private string _TractorVisualSAT;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnidConsumidorChanging(string value);
    partial void OnidConsumidorChanged();
    partial void OntractorImplementoChanging(string value);
    partial void OntractorImplementoChanged();
    partial void OnPropioAlquiladoChanging(string value);
    partial void OnPropioAlquiladoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnlineaChanging(string value);
    partial void OnlineaChanged();
    partial void OncultivoChanging(string value);
    partial void OncultivoChanged();
    partial void OnTractorVisualSATChanging(string value);
    partial void OnTractorVisualSATChanged();
    #endregion
		
		public TractorVS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsumidor", DbType="Char(12)")]
		public string idConsumidor
		{
			get
			{
				return this._idConsumidor;
			}
			set
			{
				if ((this._idConsumidor != value))
				{
					this.OnidConsumidorChanging(value);
					this.SendPropertyChanging();
					this._idConsumidor = value;
					this.SendPropertyChanged("idConsumidor");
					this.OnidConsumidorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tractorImplemento", DbType="VarChar(50)")]
		public string tractorImplemento
		{
			get
			{
				return this._tractorImplemento;
			}
			set
			{
				if ((this._tractorImplemento != value))
				{
					this.OntractorImplementoChanging(value);
					this.SendPropertyChanging();
					this._tractorImplemento = value;
					this.SendPropertyChanged("tractorImplemento");
					this.OntractorImplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropioAlquilado", DbType="VarChar(50)")]
		public string PropioAlquilado
		{
			get
			{
				return this._PropioAlquilado;
			}
			set
			{
				if ((this._PropioAlquilado != value))
				{
					this.OnPropioAlquiladoChanging(value);
					this.SendPropertyChanging();
					this._PropioAlquilado = value;
					this.SendPropertyChanged("PropioAlquilado");
					this.OnPropioAlquiladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linea", DbType="VarChar(50)")]
		public string linea
		{
			get
			{
				return this._linea;
			}
			set
			{
				if ((this._linea != value))
				{
					this.OnlineaChanging(value);
					this.SendPropertyChanging();
					this._linea = value;
					this.SendPropertyChanged("linea");
					this.OnlineaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cultivo", DbType="VarChar(50)")]
		public string cultivo
		{
			get
			{
				return this._cultivo;
			}
			set
			{
				if ((this._cultivo != value))
				{
					this.OncultivoChanging(value);
					this.SendPropertyChanging();
					this._cultivo = value;
					this.SendPropertyChanged("cultivo");
					this.OncultivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TractorVisualSAT", DbType="Char(12)")]
		public string TractorVisualSAT
		{
			get
			{
				return this._TractorVisualSAT;
			}
			set
			{
				if ((this._TractorVisualSAT != value))
				{
					this.OnTractorVisualSATChanging(value);
					this.SendPropertyChanging();
					this._TractorVisualSAT = value;
					this.SendPropertyChanged("TractorVisualSAT");
					this.OnTractorVisualSATChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Semana")]
	public partial class Semana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private System.Nullable<int> _anio;
		
		private System.Nullable<int> _semana1;
		
		private System.Nullable<System.DateTime> _desde;
		
		private System.Nullable<System.DateTime> _hasta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void Onsemana1Changing(System.Nullable<int> value);
    partial void Onsemana1Changed();
    partial void OndesdeChanging(System.Nullable<System.DateTime> value);
    partial void OndesdeChanged();
    partial void OnhastaChanging(System.Nullable<System.DateTime> value);
    partial void OnhastaChanged();
    #endregion
		
		public Semana()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
		public System.Nullable<int> anio
		{
			get
			{
				return this._anio;
			}
			set
			{
				if ((this._anio != value))
				{
					this.OnanioChanging(value);
					this.SendPropertyChanging();
					this._anio = value;
					this.SendPropertyChanged("anio");
					this.OnanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="semana", Storage="_semana1", DbType="Int")]
		public System.Nullable<int> semana1
		{
			get
			{
				return this._semana1;
			}
			set
			{
				if ((this._semana1 != value))
				{
					this.Onsemana1Changing(value);
					this.SendPropertyChanging();
					this._semana1 = value;
					this.SendPropertyChanged("semana1");
					this.Onsemana1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desde", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> desde
		{
			get
			{
				return this._desde;
			}
			set
			{
				if ((this._desde != value))
				{
					this.OndesdeChanging(value);
					this.SendPropertyChanging();
					this._desde = value;
					this.SendPropertyChanged("desde");
					this.OndesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasta", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> hasta
		{
			get
			{
				return this._hasta;
			}
			set
			{
				if ((this._hasta != value))
				{
					this.OnhastaChanging(value);
					this.SendPropertyChanging();
					this._hasta = value;
					this.SendPropertyChanged("hasta");
					this.OnhastaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SAS_ListadoPartesDeMaquinariaPorSemanaResult
	{
		
		private string _idpartemaq;
		
		private string _fecha;
		
		private string _PERIODO;
		
		private string _idTurnoTrabajo;
		
		private string _documento;
		
		private string _idMaquinaria;
		
		private string _maquinaria;
		
		private string _idImplemento;
		
		private string _ITEM;
		
		private string _idConsumidor;
		
		private string _consumidor;
		
		private System.Nullable<decimal> _HORAINICIO;
		
		private System.Nullable<decimal> _HORAFINAL;
		
		private decimal _HORAS_TRAB;
		
		private decimal _HOROMETROINICIAL;
		
		private System.Nullable<decimal> _HOROMETROFINAL;
		
		private System.Nullable<decimal> _diferencia;
		
		private string _idActividad;
		
		private string _actividad;
		
		private string _idLabor;
		
		private string _labor;
		
		private string _IDENTIFICADOr;
		
		private System.Nullable<int> _año;
		
		private System.Nullable<int> _trimestre;
		
		private System.Nullable<int> _semana;
		
		private System.Nullable<int> _nroMes;
		
		private System.Nullable<int> _dia;
		
		private System.Nullable<int> _numeroDeDiaEnLaSemana;
		
		private System.Nullable<int> _nroDiaDelAnio;
		
		private string _NombreDiaSemana;
		
		private string _nombreMes;
		
		public SAS_ListadoPartesDeMaquinariaPorSemanaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpartemaq", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string idpartemaq
		{
			get
			{
				return this._idpartemaq;
			}
			set
			{
				if ((this._idpartemaq != value))
				{
					this._idpartemaq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="VarChar(20)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODO", DbType="Char(6)")]
		public string PERIODO
		{
			get
			{
				return this._PERIODO;
			}
			set
			{
				if ((this._PERIODO != value))
				{
					this._PERIODO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTurnoTrabajo", DbType="Char(2)")]
		public string idTurnoTrabajo
		{
			get
			{
				return this._idTurnoTrabajo;
			}
			set
			{
				if ((this._idTurnoTrabajo != value))
				{
					this._idTurnoTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="VarChar(20)")]
		public string documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this._documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMaquinaria", DbType="VarChar(12)")]
		public string idMaquinaria
		{
			get
			{
				return this._idMaquinaria;
			}
			set
			{
				if ((this._idMaquinaria != value))
				{
					this._idMaquinaria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maquinaria", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string maquinaria
		{
			get
			{
				return this._maquinaria;
			}
			set
			{
				if ((this._maquinaria != value))
				{
					this._maquinaria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idImplemento", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string idImplemento
		{
			get
			{
				return this._idImplemento;
			}
			set
			{
				if ((this._idImplemento != value))
				{
					this._idImplemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string ITEM
		{
			get
			{
				return this._ITEM;
			}
			set
			{
				if ((this._ITEM != value))
				{
					this._ITEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsumidor", DbType="VarChar(12)")]
		public string idConsumidor
		{
			get
			{
				return this._idConsumidor;
			}
			set
			{
				if ((this._idConsumidor != value))
				{
					this._idConsumidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumidor", DbType="VarChar(100)")]
		public string consumidor
		{
			get
			{
				return this._consumidor;
			}
			set
			{
				if ((this._consumidor != value))
				{
					this._consumidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAINICIO", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> HORAINICIO
		{
			get
			{
				return this._HORAINICIO;
			}
			set
			{
				if ((this._HORAINICIO != value))
				{
					this._HORAINICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAFINAL", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> HORAFINAL
		{
			get
			{
				return this._HORAFINAL;
			}
			set
			{
				if ((this._HORAFINAL != value))
				{
					this._HORAFINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAS_TRAB", DbType="Decimal(5,2) NOT NULL")]
		public decimal HORAS_TRAB
		{
			get
			{
				return this._HORAS_TRAB;
			}
			set
			{
				if ((this._HORAS_TRAB != value))
				{
					this._HORAS_TRAB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOROMETROINICIAL", DbType="Decimal(10,2) NOT NULL")]
		public decimal HOROMETROINICIAL
		{
			get
			{
				return this._HOROMETROINICIAL;
			}
			set
			{
				if ((this._HOROMETROINICIAL != value))
				{
					this._HOROMETROINICIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOROMETROFINAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> HOROMETROFINAL
		{
			get
			{
				return this._HOROMETROFINAL;
			}
			set
			{
				if ((this._HOROMETROFINAL != value))
				{
					this._HOROMETROFINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diferencia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> diferencia
		{
			get
			{
				return this._diferencia;
			}
			set
			{
				if ((this._diferencia != value))
				{
					this._diferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idActividad", DbType="VarChar(3)")]
		public string idActividad
		{
			get
			{
				return this._idActividad;
			}
			set
			{
				if ((this._idActividad != value))
				{
					this._idActividad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actividad", DbType="VarChar(50)")]
		public string actividad
		{
			get
			{
				return this._actividad;
			}
			set
			{
				if ((this._actividad != value))
				{
					this._actividad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLabor", DbType="VarChar(6)")]
		public string idLabor
		{
			get
			{
				return this._idLabor;
			}
			set
			{
				if ((this._idLabor != value))
				{
					this._idLabor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labor", DbType="VarChar(200)")]
		public string labor
		{
			get
			{
				return this._labor;
			}
			set
			{
				if ((this._labor != value))
				{
					this._labor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICADOr", DbType="VarChar(9)")]
		public string IDENTIFICADOr
		{
			get
			{
				return this._IDENTIFICADOr;
			}
			set
			{
				if ((this._IDENTIFICADOr != value))
				{
					this._IDENTIFICADOr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_año", DbType="Int")]
		public System.Nullable<int> año
		{
			get
			{
				return this._año;
			}
			set
			{
				if ((this._año != value))
				{
					this._año = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trimestre", DbType="Int")]
		public System.Nullable<int> trimestre
		{
			get
			{
				return this._trimestre;
			}
			set
			{
				if ((this._trimestre != value))
				{
					this._trimestre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semana", DbType="Int")]
		public System.Nullable<int> semana
		{
			get
			{
				return this._semana;
			}
			set
			{
				if ((this._semana != value))
				{
					this._semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroMes", DbType="Int")]
		public System.Nullable<int> nroMes
		{
			get
			{
				return this._nroMes;
			}
			set
			{
				if ((this._nroMes != value))
				{
					this._nroMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia", DbType="Int")]
		public System.Nullable<int> dia
		{
			get
			{
				return this._dia;
			}
			set
			{
				if ((this._dia != value))
				{
					this._dia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroDeDiaEnLaSemana", DbType="Int")]
		public System.Nullable<int> numeroDeDiaEnLaSemana
		{
			get
			{
				return this._numeroDeDiaEnLaSemana;
			}
			set
			{
				if ((this._numeroDeDiaEnLaSemana != value))
				{
					this._numeroDeDiaEnLaSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDiaDelAnio", DbType="Int")]
		public System.Nullable<int> nroDiaDelAnio
		{
			get
			{
				return this._nroDiaDelAnio;
			}
			set
			{
				if ((this._nroDiaDelAnio != value))
				{
					this._nroDiaDelAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDiaSemana", DbType="NVarChar(30)")]
		public string NombreDiaSemana
		{
			get
			{
				return this._NombreDiaSemana;
			}
			set
			{
				if ((this._NombreDiaSemana != value))
				{
					this._NombreDiaSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMes", DbType="NVarChar(30)")]
		public string nombreMes
		{
			get
			{
				return this._nombreMes;
			}
			set
			{
				if ((this._nombreMes != value))
				{
					this._nombreMes = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoCombustibleAbastecidosATractorPorSemanaResult
	{
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _periodo;
		
		private string _documento;
		
		private string _idConsumidor;
		
		private string _maquinaria;
		
		private string _idproducto;
		
		private string _producto;
		
		private System.Nullable<decimal> _cantidad;
		
		private string _llevadoPor;
		
		private System.Nullable<int> _año;
		
		private System.Nullable<int> _semana;
		
		private string _NombreDiaSemana;
		
		public SAS_ListadoCombustibleAbastecidosATractorPorSemanaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="Char(6)")]
		public string periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this._periodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="VarChar(20)")]
		public string documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this._documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsumidor", DbType="VarChar(12)")]
		public string idConsumidor
		{
			get
			{
				return this._idConsumidor;
			}
			set
			{
				if ((this._idConsumidor != value))
				{
					this._idConsumidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maquinaria", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string maquinaria
		{
			get
			{
				return this._maquinaria;
			}
			set
			{
				if ((this._maquinaria != value))
				{
					this._maquinaria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idproducto", DbType="VarChar(20)")]
		public string idproducto
		{
			get
			{
				return this._idproducto;
			}
			set
			{
				if ((this._idproducto != value))
				{
					this._idproducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(200)")]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this._producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(17,6)")]
		public System.Nullable<decimal> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_llevadoPor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string llevadoPor
		{
			get
			{
				return this._llevadoPor;
			}
			set
			{
				if ((this._llevadoPor != value))
				{
					this._llevadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_año", DbType="Int")]
		public System.Nullable<int> año
		{
			get
			{
				return this._año;
			}
			set
			{
				if ((this._año != value))
				{
					this._año = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semana", DbType="Int")]
		public System.Nullable<int> semana
		{
			get
			{
				return this._semana;
			}
			set
			{
				if ((this._semana != value))
				{
					this._semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDiaSemana", DbType="NVarChar(30)")]
		public string NombreDiaSemana
		{
			get
			{
				return this._NombreDiaSemana;
			}
			set
			{
				if ((this._NombreDiaSemana != value))
				{
					this._NombreDiaSemana = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoFiltroReporteVisualSAT_NISIRAResult
	{
		
		private int _codigo;
		
		private string _valor;
		
		private string _descripcion;
		
		public SAS_ListadoFiltroReporteVisualSAT_NISIRAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int NOT NULL")]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(50)")]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this._valor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
